### ISSUE TITLE
TypeError: object of type 'WebElement' has no len() 

### ISSUE THREAD

**Issue by mzbedat** [serhatbolsu/robotframework-appiumlibrary#117]
Hi,
When I attempt to click on element retrieved from Get Elements keyword (retrieve a list of elements), am getting:
TypeError: object of type 'WebElement' has no len()

`${elements}=	Get Elements	class=pmode8

	${len}=	Get Length	${elements}

	${index}=	Evaluate	random.randint(0, ${len}-1)	random

	${element}=	Get From List	${elements}	${index}

	#Click Element	${element}`

I referred back to bug #106  fix and found that I have the most updated code of _element.py.
But issue is still reproducible!!

More details, testing on:

1. Real Device (iOS 9.3.2)
2. Appium 1.5.3 - With Safari Browser

B.R.

**Comment by mzbedat** [comment]
When I used the "Get Source" keyword during debuting I realised that the webpage is actually apple.com (which opens by default when launching Safari) and not the url that I gave!

However,
I tried giving xpath (taken by inspector) or class (taken from the source code) am still getting:
WebDriverException: Message: Element is not currently visible and may not be manipulated (status: 11)

**Comment by mzbedat** [comment]
I managed to click elements by class= locator
with xpath= locator it didn't!

**Comment by leongxf** [comment]
Hi,
`Click Element` requires a locator, such as 'xpath/dom/css'.
In this case, you cannot pass a *WebElement* object to `Click Element`, which of course will raise an exception.

Here is a possible way:

case.txt
```
Library    utils.py
...
<your code>
...

${element}    Get From List    ${elements}    ${index}
Trigger Attr    ${element}    click
```

utils.py

```
def trigger_attr(obj, attribute):
    try:
        function = getattr(obj, attribute)
    except AttributeError as e:
        raise AttributeError('Given function %s does not exist in obj %s' % (obj, attribute))
    function()
```

**Comment by serhatbolsu** [comment]
I see the change you require, I have checked robotframework-selenium2library as an reference point: there is a `Get Elements` keyword. As of recent change (1.7) all `locator` 's seems to be able to receive webelement as reference (ex. click element  <webelement>).

I will check the implementation, I also believe this is an important requirement

**Comment by mzbedat** [comment]
Excellent :)
I'm using the selenium2library and I know that it's existing there. Thats why it seemed to me essential to have it here as well.

Anyway the WA provided as working well

**Comment by serhatbolsu** [comment]
@mzbedat excuse me, this is already supported and merged 62d32af5dbfdcb25b918cfec0f8d9e9c7ea9c6e9 .

What I will do is to update the documentation about usage. And also probably update the name of variable to `Get WebElements` .In the mean time try this:

```robotframework
@{elements}  Get Elements  class=android.widget.EditText
Click Element  @{elements}[0]
```

**Comment by serhatbolsu** [comment]
Please test with v1.4.0.b1 released as pre-release you can find download instructions on release description https://github.com/serhatbolsu/robotframework-appiumlibrary/releases

**Comment by serhatbolsu** [comment]
v1.4 released
