### ISSUE TITLE
Tap method implementation request!

### ISSUE THREAD

**Issue by SharanuPatted** [serhatbolsu/robotframework-appiumlibrary#122]
Hi jollychang,

Its great effort to see appium library for robot-framework. Thank you very much. But.
I am in need of Tap method of Appium Library. When I try to use it, there is an error saying yet to be implemented.

Please help and do the needful.

Thanks,
Sharanu Patted

**Comment by serhatbolsu** [comment]
Did you try ""click" methods already ? So far we have not needed tap. Please provide an example situation where click methods are not enough?
Thank you

**Comment by serhatbolsu** [comment]
I have a plan to add ``Multi Tap`` as `Tap`. So that a command can send multiple finger touch on the screen for a period of time. Would this be good solution for you?

**Comment by serhatbolsu** [comment]
Please test `Tap` as it is already in Library.

**Comment by ponkar** [comment]
Has it not been documented in Keyword Documentation ?

**Comment by serhatbolsu** [comment]
Yes, http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Tap

**Comment by serhatbolsu** [comment]
Implemented with `Tap with Positions` please check #363
