### ISSUE TITLE
Get Text of an element

### ISSUE THREAD

**Issue by serhatbolsu** [serhatbolsu/robotframework-appiumlibrary#127]
Need a new method for getting the text on the `location`

My initial research shows that this is a method from Selenium. It might be only limited to `xpath` locator. Evaluate more on needs please.

**Comment by rajenderpal** [comment]
i am also new to robotframework but its recommend that we should use CSS method to locate any element..e.g- you can give-
css=a#id name
css=a.class name
# means id
. means class

**Comment by serhatbolsu** [comment]
@rajenderpal for mobile web what you say is true however if you are testing an native app css is not valid. on Android `id` is "resource-id". on iOS need to check again but I believe accessibility-id

**Comment by serhatbolsu** [comment]
Please test with v1.4.0.b1 released as pre-release you can find download instructions on release description https://github.com/serhatbolsu/robotframework-appiumlibrary/releases

**Comment by sayaleepote** [comment]
Added Get Text keyword #135

**Comment by serhatbolsu** [comment]
@sayaleepote it was already implemented as previous comment mentions, you can directly use it by

`pip install robotframework-appiumlibrary --upgrade --pre`

**Comment by serhatbolsu** [comment]
v1.4 released
