### ISSUE TITLE
TypeError: lock() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by UlhasDeshmukh** [serhatbolsu/robotframework-appiumlibrary#130]
Hi,
When I tried to use AppiumLibrary.Lock  , I'm getting below error
TypeError: lock() takes exactly 2 arguments (1 given)

when saw appium - python binding code as below is expecting time in seconds as an argument
https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py
> def lock(self, seconds):
>         """Lock the device for a certain period of time. iOS only.
>         :Args:
>          - the duration to lock the device, in seconds
>         """

but in robot keyword we are not expecting any arguments 
https://github.com/serhatbolsu/robotframework-appiumlibrary/blob/master/src/AppiumLibrary/keywords/_applicationmanagement.py

> def lock(self):
>         """
>         Lock the device
>         """
>         self._current_application().lock()
>

**Comment by serhatbolsu** [comment]
Closed as fixed with #131
