### ISSUE TITLE
Input text does not support unicode

### ISSUE THREAD

**Issue by mekxtari** [serhatbolsu/robotframework-appiumlibrary#132]
I tried to input unicode string using input text -keyword but nothing happened. For a bit of searching i found out that appium does not support unicode string. There seems to be some kind of workaround found from here: https://github.com/appium/io.appium.android.ime that is also suggested by appium.

Wouldn't be easier to implement this inside appiumlibrary?

**Comment by serhatbolsu** [comment]
As I did some research this is related with Appium itself. 

Please check : http://appium.readthedocs.io/en/stable/en/writing-running-appium/unicode/

In Android passing `unicodeKeyboard=${TRUE}` is even enough for desiredCapabilities, I have tested it works

**Comment by mekxtari** [comment]
unicodeKeyboard=${TRUE} for desiredCapabilities seems to work perfectly!
