### ISSUE TITLE
Run a test on an existing session id

### ISSUE THREAD

**Issue by issacjohngad** [serhatbolsu/robotframework-appiumlibrary#136]
Hi,

We have a test script to check the login screen of an iOS App. The next test-script is to check the subsequent page. Our first script will Open the application with the desired capabilities and execute it successfully and quit (with out closing the application and hence the session). Next we have to execute the second script, but don't want to repeat the Open Application and the login process, as the session is still active. 
How can we achieve this? We think the session id is way to go , but how can we retrieve the session id using the  robotframework-appiumlibrary and use the session id to send commands?

**Comment by issacjohngad** [comment]
We tried the following method:

Did an Open Application with an alias (say "Testing") in the very first script.and then use this alias with a Switch Application keyword in the second script. But it was giving an error saying No alias named "Testing" when executing the second script.

**Comment by serhatbolsu** [comment]
Appium itself does not support app switch for iOS. Please first refer to http://appium.io/slate/en/master/?javascript#appium-platform-support

**Comment by issacjohngad** [comment]
Hi,

We think you are mentioning to the statement "Support for automating multiple apps in one session: No" in the link http://appium.io/slate/en/master/?javascript#appium-platform-support. 

The issue that we are trying to follow is as follows:

Let say we have an iOS Native App. It has a login screen and a Home screen (will be displayed once you successfully logged in). We have split these 2 screens (of the same app ) to 2 test scripts. We will execute the first test script using a pybot command. Once the test run is completed we would like to run the second test script (tap a button on the Home screen) using **another pybot command execution**.  
Now we haven't closed the app after the execution of the first script. So is there a way we can get the session id of the first test script run session  (using any keywords) and run the second test script on that session?
This will be a great option to have when we want to test an app with a lot of buttons and screens, want to split these into multiple scripts and want to run one test script after another using a Test management tool (like Testrail or testopia plugins), say iterate through the test cases in a test run (of the test management tool) and run one by one.

**Comment by serhatbolsu** [comment]
I dont understand why you are not using 1 test case to re-open application and continue. But still this will be a new session_id by Appium. Unfortunately Appium does not allow (for iOS) closing application and keeping the session alive
