### ISSUE TITLE
Why 

### ISSUE THREAD

**Issue by UlhasDeshmukh** [serhatbolsu/robotframework-appiumlibrary#137]
Below keywords documentation is not available on current documentation page
http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html

**Application Management Keywords**

1. get_appium_timeout
2. set_appium_timeout
3. portrait
4. landscape

**Element Keywords**

1. get_element_size
2. get_element_location
3. get_element_attribute
4. get_elements
5. element_attribute_should_match
6. element_value_should_be

**Touch Keywords**

1. scroll_to
2. click_a_point

How to include them ? or 
is latest document is not generated with LibDoc and uploaded to github pages?

**Comment by UlhasDeshmukh** [comment]
@jollychang , @serhatbolsu please advice.

**Comment by serhatbolsu** [comment]
@UlhasDeshmukh that is good catch. I dont know the reason but I will fix it.

**Comment by serhatbolsu** [comment]
@UlhasDeshmukh You can now find latest doc in http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html

There are many new stuff, thank you for reporting the error in link
