### ISSUE TITLE
Click element is not working with appium 1.6.1

### ISSUE THREAD

**Issue by syedasadulhaq** [serhatbolsu/robotframework-appiumlibrary#142]
I had update to appium1.6.1 from appium1.6.1-beta. And after that Click element function is not working.

**Comment by serhatbolsu** [comment]
can you provide some debug information @syedasadulhaq , what error did you face, do you know what is diffirent in 1.6.1-beta ?

**Comment by syedasadulhaq** [comment]
There is no error log for this. The click just don't work.

**Comment by syedasadulhaq** [comment]
The issue has been fixed at appium1.6.2 (https://github.com/appium/appium/releases).
