### ISSUE TITLE
Working with Appium 1.6 

### ISSUE THREAD

**Issue by mzbedat** [serhatbolsu/robotframework-appiumlibrary#143]
Hi,
Recently I got a Mac with osx 10.10.5 to run appium on. I installed Appium 1.5.3 (last formal release) but I couldnt establish a connection with a real ios device connected to the mac since I hadnt xcrun instruments installed.
In order to install Xcode I had to upgrade my osx to 10.12 (sierra), then I installed Xcode 8.1 with dev tools and now I can see my device when running: instruments -s devices

The problem started when I realized that appium 1.5 is not supporting ios 10.12 
For more information: [https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md)

Appium released 1.6 beta version (that doesnt have GUI and can be ran from terminal)
But when running a test that I had before and was running on 10.11.6, I got:

> WebDriverException: Message: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

Does AppiumLibrary support XCUITest?

B.R

**Comment by serhatbolsu** [comment]
Yes, for this regard please check : [Appium XCUI Doc](http://appium.io/slate/en/master/?ruby#apple-xcuitest)
