### ISSUE TITLE
Cannot set variable '@{we}': Expected list-like value, got WebElement.

### ISSUE THREAD

**Issue by chetand24** [serhatbolsu/robotframework-appiumlibrary#146]
When we call "Get webelements" the return is not list-like when we have only one element.

Got following error message when tried:
      Cannot set variable '@{we}': Expected list-like value, got WebElement.

**Comment by serhatbolsu** [comment]
Did you try "Set Variable  ${we}" . I think build-in library is not good to handle actual for of robot objects.

**Comment by chetand24** [comment]
@serhatbolsu I am getting list of webelements when there are more then one element but it doesn't return list when its only one element. 

In any case the "Get webelements" should always return list

**Comment by serhatbolsu** [comment]
I have not tested it, since you confirm the issue, can you make a pull request ?

**Comment by serhatbolsu** [comment]
resolved with #249
