### ISSUE TITLE
Cannot Swipe From Bottom To Top

### ISSUE THREAD

**Issue by MaisGurbanov** [serhatbolsu/robotframework-appiumlibrary#151]
Hello,

After trying to swipe from bottom to top by using below combinations, there is no success result:

swipe (100, 100, 0, 20)
swipe (100, 100, 0, -20)
swipe (100, 100, 20, 0)
swipe (100, 100, -20, 0)

Appium Version: 1.6.3
Framework: RobotFramework
Device: iPhone 5 (320pts x 568pts)
IDE: PyCharm

**Comment by serhatbolsu** [comment]
@MaisGurbanov  for iOS it works as offset. 
`swipe (100, 100, 0, -20)` should have worked. There are times Appium does not work for iOS, then it solves to pick a different point. For example: `swipe  200  200  0  -50`

**Comment by MaisGurbanov** [comment]
Dear @serhatbolsu,

Thank you for your response. I had tried as you mentioned but it is still not working properly. Instead of swiping from bottom to top, it swipes from left to right.

**Comment by serhatbolsu** [comment]
I also wonder what happens when you do without using offset ?

```
swipe  ${200}  ${200}  ${200}  ${150}
```
