### ISSUE TITLE
Swipe is not working at iOS

### ISSUE THREAD

**Issue by syedasadulhaq** [serhatbolsu/robotframework-appiumlibrary#154]
Problem: It clicks on the initial co-ordinates (both on real device & simulator)

Example: 
   ${start_x}=   Convert To Integer    252
   ${start_y}=   Convert To Integer    504
   ${offset_x}=   Convert To Integer    0
   ${offset_y}=   Convert To Integer    -200
   Swipe   ${start_x}   ${start_y}   ${offset_x}   ${offset_y}   1000

it selects the initial co-ordinates and press that. I changed the duration to even 20000, but still the same. 
Appium Log:

{"sessionId":"24989c8d-5ba4-4428-89e6-549c89535eb2","actions":[{"action":"press","options":{"y":504,"x":252}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":-200,"x":0}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":504,"x":252}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":-200,"x":0}},{"action":"release","options":{}}],"24989c8d-5ba4-4428-89e6-549c89535eb2"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-release

Appium version: 1.6.3
appiumlibrary: 1.4.2

**Comment by syedasadulhaq** [comment]
Seems to moveTo action is not working

**Comment by syedasadulhaq** [comment]
seems like a known issue with appium1.6.3: https://github.com/appium/appium/issues/7550

**Comment by dilsreccse** [comment]
tried swipe using 1.6.4 beta version, in that swipe from bottom to top is not working, <script src="https://gist.github.com/dilsreccse/a9682d833be0bad968852caa5dabc2cc.js"></script>

**Comment by serhatbolsu** [comment]
Sould be resolved now, closing issue
