### ISSUE TITLE
KeyError: 'platformName'

### ISSUE THREAD

**Issue by chenry44** [serhatbolsu/robotframework-appiumlibrary#155]
Hello,

Im using the appiumlibrary 1.4.2, the 'open application' function is working fine (chrome), same for 'Go to url'. But when, im trying to manipulate a webpage like a cleartext or a click element i get an error :  

KeyError: 'platformName'

If i use an older version of the library (1,3.5) its working fine.

Thanks.

My settings : 

Appium client : 1.4.16.01

AppiumLibrary.Open Application    127.0.0.1:10002    platformName=Android    platformVersion=5.1.1    browserName=chrome    deviceName=Samsung

**Comment by serhatbolsu** [comment]
Can you share more information about issue;
- Appium Log
- Test case script

**Comment by chenry44** [comment]
In the zip, appium log and script which is quite simple

[Issue.zip](https://github.com/serhatbolsu/robotframework-appiumlibrary/files/735354/Issue.zip)

**Comment by chenry44** [comment]
Thanks btw

**Comment by serhatbolsu** [comment]
#156 Please check explain
