### ISSUE TITLE
 Input are sometime replaced 

### ISSUE THREAD

**Issue by tesseslol** [serhatbolsu/robotframework-appiumlibrary#157]
i'm using appium (by robotframework) to make a simple login test on a mobile app.
the test sometime works fine,
sometime, as you can see in the video hosted in youtube, the last character is deleted.

i tried to give some resting time using some delays, but nothing changed.

this is my code with the test (1:10 min for code):
https://youtu.be/-q-UCUkspIQ

is this an issue?

thanks

**Comment by serhatbolsu** [comment]
Hello @tesseslol ,

I have seen this issue before. I think I can help you.

1- use the selector directly:
I see your have written "id" as "id=${APP_PACKAGE}:id/username"
instead just write:
"id=username", this should do it. And if you are using library version 1.4.2 you dont even need to specify "id" as selector so it becomes "username" only.

2- that action of deleting the last character is actually behaviour of trying to clear field (failing though) before clicking. This means that selecting the password field was not successful. Probable reason can be , keyboard is open an field is not selectable. So try to use: "hide keyboard" after input username.

**Comment by tesseslol** [comment]
Now the input is Working !!! but the click elements doesn't work now...
Video of the problem:
https://youtu.be/7YLDgGyA-C4

Thanks for the help

**Comment by serhatbolsu** [comment]
Well that is about the locator you are using, try other ways if "id" does not.

You could try
'''
click text GO
'''

BR

Serhat BOLSU

**Comment by tesseslol** [comment]
ValueError: Element locator '//*[contains(@text,"GO")]' did not match any elements.

**Comment by tesseslol** [comment]
With a delay click element work ...
