### ISSUE TITLE
Swipe offsets not working correctly for iOS or incorrectly documented

### ISSUE THREAD

**Issue by DVeautour** [serhatbolsu/robotframework-appiumlibrary#173]
robotframework == 3.0.2
robotframework-appiumlibrary==1.4.3
iOS==10.3 (14E277)

Swipe is concatenating the offsets to the starting positions of x and y for XCUITest.
RF example similar to documented:
Swipe    50    50    100    100

appium log:
[debug] [XCUITest] Received the following touch action: press(options={"y":"50","x":"50"})-wait(options={"ms":1000})-moveTo(options={"y":"100","x":"100"})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/48954E87-4F28-41F4-97AD-C1ACB4BC218D/wda/dragfromtoforduration] with body: {"fromX":"50","fromY":"50","toX":"50100","toY":"50100","duration":1}

You can see the toX and toY values are string concatenations.

If you cast the parameters to ints, it works correctly:
${xstart} =    Convert To Integer  50
${ystart} =    Convert To Integer  50
${xoffset} =    Convert To Integer  100
${yoffset} =    Convert To Integer  100

appium log:
[debug] [XCUITest] Received the following touch action: press(options={"y":50,"x":50})-wait(options={"ms":1000})-moveTo(options={"y":100,"x":100})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/18763148-04B8-4DFF-AA65-75B970B8879E/wda/dragfromtoforduration] with body: {"fromX":50,"fromY":50,"toX":150,"toY":150,"duration":1}

Here the offsets are correctly added to the initial x,y positions.

**Comment by serhatbolsu** [comment]
Try new keyword `Swipe By Percent` also this considers that iOS and Android behaves differently
