### ISSUE TITLE
'run on failure' with python 3

### ISSUE THREAD

**Issue by gabribela** [serhatbolsu/robotframework-appiumlibrary#186]
Hi.
thanks for your great effort for the python 3 compatibility.
Unfortunately the "run-on-failure" functionality doesn't work on python 3.  I guess, a reason could be the metaclass in "keywordgroup.py". 

```python
class KeywordGroup(object):
    __metaclass__ = KeywordGroupMetaClass 
```

Metaclasses have changed in python 3:

```python
# Python 2 and 3:
from six import with_metaclass
# or
from future.utils import with_metaclass

class Form(with_metaclass(FormType, BaseForm)):
    pass

```
from: http://python-future.org/compatible_idioms.html

May anyone please check this? Thank you so much.

kind regards,
gabriela

**Comment by lolotoms** [comment]
Hi 

I tried update keywordgroup.py with code you shared. I replace

class KeywordGroup(object):
    __metaclass__ = KeywordGroupMetaClass

by

class KeywordGroup(with_metaclass(KeywordGroupMetaClass, object)):
    pass

and add import
from six import with_metaclass

It works fine with python 3.5.2 but I haven't test it with python 2.7

**Comment by serhatbolsu** [comment]
@lolotoms great work. Can you test with Py 2.7 and create a pull request for contribution?

**Comment by lolotoms** [comment]
Yes, I will do that this week end :)

**Comment by gabribela** [comment]
@lolotoms wow, that is great. Thank you so much for your efforts!

**Comment by matthewdy** [comment]
@lolotoms @gabribela thanks for the investigation. Why don't we create a pull request ?
