### ISSUE TITLE
locator strategy : Find one id or another 

### ISSUE THREAD

**Issue by lolotoms** [serhatbolsu/robotframework-appiumlibrary#199]
Hi,

I write scripts which have to run on tablet and smartphone. Time to time xpath are differents. So I use a variable which is looking for one xpath are the other:

${var}    xpath=(//android.widget.TextView[@resource-id="value1"] | //android.widget.TextView[@resource-id="value2"]) [1]

This works fine. RF return TRUE if one of these two xpath is find. I'm looking to a similar solution to do the same with id:

either declare one variable like for xpath:
${var}    id=(id1 | id2)[1]

or declare two variables and find one or the other:
${var1}    id=value1
${var2}    id=value2
Click element    ${var1} or ${var2}    

I tried the both above and it doesn't work. 

Do you have any suggest please?

**Comment by serhatbolsu** [comment]
You should be able to create such a condition with `Run Keyword and Ignore Error`
