### ISSUE TITLE
long_press does not have duration

### ISSUE THREAD

**Issue by kshrestha99** [serhatbolsu/robotframework-appiumlibrary#202]
would it be possible to add parameter `duration` to the method long_press? The long_press method in python-client/appium/webdriver/common/touch_action.py has duration as one of the arguments. But it was dropped in AppiumLibrary. It would be very useful to have this duration for places where duration 1000 is not enough or too much.

**Comment by serhatbolsu** [comment]
touch methods are deprecated now with #363 please test there
