### ISSUE TITLE
ValueError: Element locator with prefix 'class' is not supported

### ISSUE THREAD

**Issue by JaldhiPandya** [serhatbolsu/robotframework-appiumlibrary#204]

**Comment by abhijitbangera** [comment]
Even I am observing this issue.
`ValueError: Element locator with prefix 'class' is not supported`

**Comment by inarvekar** [comment]
Getting same error 
ValueError: Element locator with prefix '(//div[@class' is not supported

**Comment by tbrown9164** [comment]
Any update on this?   I've had this problem for some time.   A Click Element works fine,  but any of the conditional keywords e.g. element Should Be Visible, Wait Until Page Contains Element etc. fail in this way:    e.g.  
Works great:  Wait Until Keyword Succeeds     5x    3 sec    Click Element   xpath= //*[@class='android.widget.Button' and ./parent::*[(./preceding-sibling::* | ./following-sibling::*)[contains(@contentDescription,'Sticky')]]]

fails with the 'not supported' message:  
 Wait Until Page Contains Element    xpath= //*[@class='android.widget.Button' and ./parent::*[(./preceding-sibling::* | ./following-sibling::*)[contains(@contentDescription,'Sticky')]]]
