### ISSUE TITLE
When running a .robot file, get error: Importing test library 'AppiumLibrary' failed: ImportError: No module named six

### ISSUE THREAD

**Issue by Jitarinc** [serhatbolsu/robotframework-appiumlibrary#208]
When I run a .robot file using a pybot command, I get this error

```
Error in file '/Users/jitarinc/bluecrystalwebadminuitest/Resource.android.robot': Importing test library 'AppiumLibrary' failed: ImportError: No module named six
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/__init__.py", line 4, in <module>
    from AppiumLibrary.keywords import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/keywords/__init__.py", line 5, in <module>
    from ._element import _ElementKeywords
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/keywords/_element.py", line 3, in <module>
    from AppiumLibrary.locators import ElementFinder
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/locators/__init__.py", line 3, in <module>
    from .elementfinder import ElementFinder
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/locators/elementfinder.py", line 3, in <module>
    from AppiumLibrary import utils
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/utils/__init__.py", line 1, in <module>
    import six
PYTHONPATH:
  /Library/Frameworks/Python.framework/Versions/2.7/bin
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg
```

**Comment by fatenBAB** [comment]
Hi Jitarinc,

Did you find the solution for this please?
I'm having the same problem right now :(

Thank you so much

**Comment by fatenBAB** [comment]
> When I run a .robot file using a pybot command, I get this error
> 
> ```
> Error in file '/Users/jitarinc/bluecrystalwebadminuitest/Resource.android.robot': Importing test library 'AppiumLibrary' failed: ImportError: No module named six
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/__init__.py", line 4, in <module>
>     from AppiumLibrary.keywords import *
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/keywords/__init__.py", line 5, in <module>
>     from ._element import _ElementKeywords
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/keywords/_element.py", line 3, in <module>
>     from AppiumLibrary.locators import ElementFinder
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/locators/__init__.py", line 3, in <module>
>     from .elementfinder import ElementFinder
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/locators/elementfinder.py", line 3, in <module>
>     from AppiumLibrary import utils
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg/AppiumLibrary/utils/__init__.py", line 1, in <module>
>     import six
> PYTHONPATH:
>   /Library/Frameworks/Python.framework/Versions/2.7/bin
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
>   /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotframework_appiumlibrary-1.4.6-py2.7.egg
> ```

Hi Jitarinc,

Did you find the solution for this please?
I'm having the same problem right now :(

Thank you so much
