### ISSUE TITLE
When using method `pinch`, I am getting an error message

### ISSUE THREAD

**Issue by kshrestha99** [serhatbolsu/robotframework-appiumlibrary#213]
Using `pinch(locator, percent="150%", steps=1)` gives this error message: "WebDriverException: Message: Unknown mobile command "pinchClose". Only shell commands are supported"

**Comment by serhatbolsu** [comment]
`Pinch` refers to original implementation in appium/python-client. It seems like this method needs to be re-written either to support http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/
or as a combination of moves as it was written in 
https://github.com/appium/java-client/commit/6b216815411a0d7ddf1679c1ceb0c10c5a779b3d#diff-f50beb490f1d493c61c0e8d7a963e5e8

**Comment by serhatbolsu** [comment]
Deprecated with #363
