### ISSUE TITLE
When using zoom method, getting an error message

### ISSUE THREAD

**Issue by kshrestha99** [serhatbolsu/robotframework-appiumlibrary#214]
Using zoom(locator, "150%") gives this error message: "WebDriverException: Message: Method has not yet been implemented"

**Comment by serhatbolsu** [comment]
`Zoom`  or ("pinchOpen") refers to original implementation in appium/python-client. It seems like this method needs to be re-written either to support http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/
or as a combination of moves as it was written in 
https://github.com/appium/java-client/commit/6b216815411a0d7ddf1679c1ceb0c10c5a779b3d#diff-f50beb490f1d493c61c0e8d7a963e5e8

**Comment by matthewdy** [comment]
I think I can help on this. @serhatbolsu

**Comment by serhatbolsu** [comment]
Zoom doesn't work anymore with #363
