### ISSUE TITLE
Use Class Chain and Predicate to locate elements on iOS

### ISSUE THREAD

**Issue by lolotoms** [serhatbolsu/robotframework-appiumlibrary#215]
Hi,

All my tests are written with id or xpath locator. I am looking for a solution to replace xpath locator by a quickly strategy locator. Appium use Class chain and predicate iOS. Do AppiumLibrary accept this strategy? How can I use it?

The appiumLibrary documentation don't give informations about that.. There is "ios" strategy but it is only for uiautomation framework. I use XCUITest driver.

 http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html

![image](https://user-images.githubusercontent.com/13163619/36741584-ca81d070-1be5-11e8-8cab-990c575d0bb6.png)

Please help me !!

**Comment by sharecommute** [comment]
@lolotoms , looks like its been implemented. Here is log output from appiumlibrary, concentrate on the valid locator stratergies.

[debug] [W3C] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeAlert","72950d73-7513-4ad4-9def-6b4970679c5c"]
[debug] [XCUITest] Executing command 'findElements'
**[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id**
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:25352/session/B5101C76-4BEB-4FA6-994A-7B5D75B016E3/elements] with body: {"using":"xpath","value":"//XCUIElementTypeAlert"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"9B1C0000-0000-0000-3800-000000000000"}],"sessionId":"B5101C76-4BEB-4FA6-994A-7B5D75B016E3","status":0}
[debug] [W3C] Responding to client with driver.findElements() result: [{"ELEMENT":"9B1C0000-0000-0000-3800-000000000000"}]

**Comment by lalamini** [comment]
you can refer this https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/196

**Comment by Kitty2014** [comment]
did Class Chain and Predicate release？

**Comment by cplus02** [comment]
Hi all, so it's not yet supported right?  While Appium has already support predicate, hope it will be coming soon.

**Comment by erik1510** [comment]
this was released in latest version (1.5.0.2)
