### ISSUE TITLE
Is there existing keyword to determine specific application running or not?

### ISSUE THREAD

**Issue by CharmingYang0** [serhatbolsu/robotframework-appiumlibrary#223]
Now I'm testing an Android application which force to select YES or NO for a disclaimer in initial lauching, if NO is chosen the app will quit.
I want to know is there any keyword (such as 'Application Should Not Running') for this?
If not, giving some workaround solution via adopting available keywords (in other packages is OK) is appreciated as well.

**Comment by serhatbolsu** [comment]
Yes you can get the package name but I am not sure if this will gurantee that you get an on-screen app details versus getting the session information
Please check this in Appium forum first.
