### ISSUE TITLE
Notification Alert appear before app is open

### ISSUE THREAD

**Issue by lolotoms** [serhatbolsu/robotframework-appiumlibrary#224]
Hi,

I am facing an issue with android alert. A notification popup appears before the app is open. So it seems that I can't interact with it. Appium is looking for activity and package application, but doesn't find it because there are in the background. Is there a way to close this popup ?

**Comment by serhatbolsu** [comment]
There is an easy fix for this, send addtional appium parameter to Open Application command;
`autoGrantPermissions=${TRUE}`
