### ISSUE TITLE
'Swipe' is not working on webview - 'Swipe by percent' is not working on both native and webview

### ISSUE THREAD

**Issue by vnvbsudhakar** [serhatbolsu/robotframework-appiumlibrary#226]
Environment:
Android 7.0, genymotion emulator, Samsung T365 Tab
Appiumlibrary 1.4.6, Python 3
Appium Desktop 1.6.2
App type: cordova app (So it is webview)

'Swipe' is not working on webview - 'Swipe by percent' is not working on both native and webview

**Comment by serhatbolsu** [comment]
Are you sure you are giving the correct coordinates?

**Comment by serhatbolsu** [comment]
@vnvbsudhakar  I have tested with Python2.7 
Appium 1.10 its working, dont have cordova app to test though
