### ISSUE TITLE
When I swipe between SeleniumLibrary and AppiumLibrary the Keyword "Tap" stops works.

### ISSUE THREAD

**Issue by douglas-zapalago** [serhatbolsu/robotframework-appiumlibrary#232]
On my project i use web and mobile on the same test case. When i swipe between SeleniumLibrary and AppiumLibrary, the Keyword "Tap", stops works.

I tryed use the Keyword "Set Library Search Order    AppiumLibrary" but, does't works.

RobotFramework Error: **WebDriverException: Message: Method has not yet been implemented**

**Comment by KazuCocoa** [comment]
Which Appium Python client version do you use?
If you're using appium-python library under 0.27, some implementation is missing for latest Appium.

Try out 0.28 after `pip install Appium-Python-Client --upgrade`.

**Comment by douglas-zapalago** [comment]
I'm using the latest version.

> TestCases git:(master) ✗ pip install Appium-Python-Client --upgrade

> Requirement already up-to-date: Appium-Python-Client in /usr/local/lib/python3.7/site-packages (0.28)

> Requirement already satisfied, skipping upgrade: selenium>=2.47.0 in /usr/local/lib/python3.7/site-packages (from Appium-Python-Client) (3.14.0)

> Requirement already satisfied, skipping upgrade: urllib3 in /usr/local/lib/python3.7/site-packages (from selenium>=2.47.0->Appium-Python-Client) (1.23)

**Comment by KazuCocoa** [comment]
Thanks!
I'm not familiar with this framework itself, but I probably dig into appium-python-client.

Can you give me the appium server log?
if it is because of appium-python-client, I'd like to fix it.

**Comment by serhatbolsu** [comment]
> When i swipe between SeleniumLibrary and AppiumLibrary, the Keyword "Tap", stops works.
Can you aloborate what does this mean?

**Comment by yst8493182** [comment]
Should be through Wda on the iOS application test, WDA does not support appium tap, swipe ...
Workaround: [document](http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/index.html#automating-mobile-gestures-for-ios-with-webdriveragentxctest-backend)

**Comment by serhatbolsu** [comment]
This is an issue of Appium not robotframework-AppiumLibrary , closing
