### ISSUE TITLE
Unable to use Appium Library keywords - Scroll, Scroll Up and Scroll down.

### ISSUE THREAD

**Issue by Sanbr5** [serhatbolsu/robotframework-appiumlibrary#240]
Appium Library Version: 1.5.0.1

I'm unable to scroll using the keywords, Scroll, Scroll Up and Scroll down.

Example: When i write,
scroll down  android=UiScrollable(UiSelector()).scrollIntoView(descriptionContains("WebView"))

i get error as: WebDriverException: Message: Unknown mobile command "scroll". Only shell,startLogsBroadcast,stopLogsBroadcast,performEditorAction commands are supported.

I do see that scroll happens on the screen but does not go to last element 'WebView'.

Kindly let me know if i'm passing wrong argument or it's actually on issue.

**Comment by serhatbolsu** [comment]
Scroll keywords are not that usefull and Android native is somewhat not supported by appium.
I suggest you to use `swipe by percent`
