### ISSUE TITLE
1.5.0.2 release does not contain the whl-package

### ISSUE THREAD

**Issue by karniemi** [serhatbolsu/robotframework-appiumlibrary#242]
Hi,

1.5.0.2 release does not contain the whl-package. Is this on purpose?

(I'm asking, because installing the 1.5.0.2 on Windows 10 using pipenv failed miserably. I now locked 1.5.0.1, which installed fine.)

**Comment by serhatbolsu** [comment]
Releasing 1.5.0.3 please check @karniemi 
thank you
