### ISSUE TITLE
Encountered internal error running command: TypeError: Class constructor BaseDriver cannot be invoked without 'new'

### ISSUE THREAD

**Issue by coolshree4u** [serhatbolsu/robotframework-appiumlibrary#244]
I am using robot framework for automation in that am using Appium Library While launching am facing error that Encountered internal error running command: TypeError: Class constructor BaseDriver cannot be invoked without 'new'

```
Open Application    http://localhost:4723/wd/hub
   platformName=iOS
  platformVersion=12.1
    deviceName=iPhone 6
      app=${build_path}       automationName=appium            bundleId=${BUNDLE_ID}
```

Environment:
Appium version (or git revision) that exhibits the issue: Appium v1.9.1
Desktop OS/version used to run Appium: Mac
Node.js version (unless using Appium.app|exe): v10.15.0
Npm or Yarn package manager: npm 6.4.1
Mobile platform/version under test: iOS
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: CLI
*** Intentionally removed app name and bundle id from stack trace
https://gist.github.com/coolshree4u/d66485579b3e9da1e48ab49be7809065

Same capabilities tried with appium-desktop v1.10.0 and able to launch application without an error.

**Comment by serhatbolsu** [comment]
so I guess, using newer version fixed this issue ?

**Comment by serhatbolsu** [comment]
I am going to close due to inactivity, @coolshree4u is your issue closed ? 
else please try with latest version of ilbrary

**Comment by coolshree4u** [comment]
Yes, this issue was regarding the wrong installation configuration. @serhatbolsu  you can close this issue.
