### ISSUE TITLE
1 improve, 1 future propose - my propose

### ISSUE THREAD

**Issue by ByJacob** [serhatbolsu/robotframework-appiumlibrary#245]
Hi 
I write task with 2 issues:
- change parameter name from stopAppOnReset to dontStopAppOnReset when execute activity (http://appium.io/docs/en/commands/device/activity/start-activity/)
- add possible execute command in device (http://appium.io/docs/en/commands/mobile-command/, https://appiumpro.com/editions/3)

Regards
Jakub Rosa

**Comment by serhatbolsu** [comment]
Parameter name: Fixed with #249  
Execute script command already exists in library : (even thought description should be updated) 
http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Execute%20Script

**Comment by ByJacob** [comment]
> Execute script command already exists in library : (even thought description should be updated)
> http://serhatbolsu.github.io/robotframework-appiumlibrary/AppiumLibrary.html#Execute%20Script

So, i have a request. Can you write example how use Execute Script in RobotFramework (for example how use adb shell)

**Comment by paparent** [comment]
@serhatbolsu I'm trying to send a "mobile:shell" command too, but it says that i need only one argument. And reading the docs, it says it's in Web context only to send JS.

Can we have an example?
