### ISSUE TITLE
Connecting to remote Appium through proxy

### ISSUE THREAD

**Issue by leonalliander** [serhatbolsu/robotframework-appiumlibrary#248]
In my current situation, I am running tests to a remote Appium instance (so I am not running Appium on my laptop). 

I have no trouble connecting to this remote Appium instance while on the internet. However, while working behind a (corporate) proxy I am unable to connect.

The proxy we have here is a simple http proxy without authentication. Is there a way to connect to a remote Appium instance through a proxy?

**Comment by serhatbolsu** [comment]
This library simply uses appium server ip:port to connect. There is no option to setup a passthrough proxy. However you can setup a proxy server yourself if thats your only problem. Alternatively look for selenium hub (using appium) installations.
