### ISSUE TITLE
Latest documentation shows Swipe by Direction

### ISSUE THREAD

**Issue by evanoktavians** [serhatbolsu/robotframework-appiumlibrary#252]
Swipe by direction is still not implemented, yet the documentation has this function already. Can this be removed or updated somehow?

**Comment by NeliHarbuzava** [comment]
I got errror that no 'Swipe By Direction' method

**Comment by ttturkey** [comment]
It is still not implemented but it is in the documentation

**Comment by NeliHarbuzava** [comment]
@ttturkey for what reason it is in the docs?

**Comment by ttturkey** [comment]
> what reason it is in the docs?

I just find this issue and I have no idea too . Just to comment here the issue is still there

**Comment by NeliHarbuzava** [comment]
> > what reason it is in the docs?
> 
> I just find this issue and I have no idea too . Just to comment here the issue is still there

ok, I get it

**Comment by Wolfe1** [comment]
@serhatbolsu any word on this? doesn't seem to be anywhere in the code that I can find but appears in the documentation.

**Comment by Wolfe1** [comment]
Seems this was an attempt in #239 but locally I get the same error as noted by @serhatbolsu

**Comment by serhatbolsu** [comment]
Please check https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/363 execute_script if that works for you. You can create an issue of it doesn't suffice
