### ISSUE TITLE
run_on_failure(Capture Page Screenshot) Fail

### ISSUE THREAD

**Issue by lynnchma** [serhatbolsu/robotframework-appiumlibrary#264]
#### Environment
OS：Windows 7

Python 3.7.2
robotframework                          3.1.2
robotframework-appiumlibrary            1.5.0.4
robotframework-databaselibrary          1.2.4
robotframework-extendedselenium2library 0.9.2
robotframework-ride                     1.7.3.1
robotframework-selenium2library         3.0.0
robotframework-seleniumlibrary          3.3.1

Appium Desktop                   1.13.0

#### Appium Log
![FAIL](https://user-images.githubusercontent.com/7628389/65826798-89cb2900-e2bd-11e9-999a-094913a095bc.png)

#### RobotFramwork Log

![test](https://user-images.githubusercontent.com/7628389/65826847-34dbe280-e2be-11e9-8ba5-aac4835e08d7.png)

#### Description
I tried setting ""run_on_failure" to "Capture Page Screenshot",but when the testcase failed,the program didn’t end immediately,it seemed to me that it stucked in running "Capture Page Screenshot”for almost ten mins,but it could end immediately when I set "run_on_failure" to "No Operation".However,when I test function “Capture Page Screenshot”separately,it works fine.I do really want that when the testcase fails it could run “Capture Page Screenshot”and end immediately,so what should I do?is it possible that something is wrong with my settings?Thanks

**Comment by serhatbolsu** [comment]
It seems the session is dead as `run_on_failure` capture  try to execute. 
Please share me the sample of your test case , including where you setup /  teardown the test.

**Comment by lynnchma** [comment]
I'm sorry  fo reply so late .

*** Settings ***
Suite Setup       打开微信
Suite Teardown    关闭
Test Setup        数据准备
Test Teardown
Library           AppiumLibrary    run_on_failure=AppiumLibrary.Capture Page Screenshot    # run_on_failure=No Operation

*** Keywords ***
数据准备
    ${suit}    Evaluate    '${SUITE_NAME}'.split('.')[-1]
    Import Variables    ${CURDIR}\\UI\\${suit}.yaml
    Import Library    ${CURDIR}\\Data\\${suit}.py
打开微信
    ${devices}    cmdUtil.get_devices
    Set Global Variable    ${SN}    ${devices[0]}
    cmdUtil.close_app    ${devices[0]}    com.tencent.mm
    ${version}    cmdUtil.get_platformversion    ${devices[0]}
    ${androidProcess}    Create Dictionary    androidProcess    com.tencent.mm:tools
    Sleep    2
    AppiumLibrary.Open Application    ${CLIENT['server']}    platformName=Android    platformVersion=${version}    deviceName=${devices[0]}    appPackage=com.tencent.mm    appActivity=.ui.LauncherUI
    ...    noReset=True    unicodeKeyboard=True    resetKeyboard=True    chromeOptions=${androidProcess}    automationName=Uiautomator2
    Run Keyword And Ignore Error    AppiumLibrary.Wait Until Element Is Visible    xpath=//*[contains(@text,'微信')]    15    

关闭
    Log    关闭程序
    AppiumLibrary.Close All Applications

*** Test Cases ***
测试
    进入首页
    加载完成
    进入订单页面
    可见点击    xpath=//div[@class='oderInfo'][1]/div/div/ion-button[contains(text(),\"ERROR\")] # Make mistakes on purpose
    已开票

**Comment by serhatbolsu** [comment]
@lynnchma run_on_failure with capture screenshot is default behaivour. 
Can you try to import the library as
`Library AppiumLibrary`  without the arguments

**Comment by lynnchma** [comment]
It’s my fault. Thank you very much!
I set "Switch To Context" to native_app,It works fine.
