### ISSUE TITLE
"Get Element Attribute" not working correctly for iOS12 after update to Appium 1.15.0 and Xcode 11

### ISSUE THREAD

**Issue by zastress** [serhatbolsu/robotframework-appiumlibrary#266]
Hello,
I have a script that runs on both iOS13 and iOS12 with the same code. 
Basically, I am using "Get Element Attribute" to fetch de value of an element (if it's disabled, it must return 0, if enabled it must return 1).
The best example is the "Wifi" button from iOS menu (see printscreen).
I open the menu on both phone and I execute `Get Element Attribute  accessibility_id=wifi-button  value`. If the Wi-fi is activated, on iOS13 I get the value of 1, which is good. But, on iOS12 I get the value 0. 
I verified with Appium inspector and the value is indeed supposed to be 1.
This was working fine until update to Appium 1.15.0 and xCode 11.

Anyone else experienced this?
![Image-1](https://user-images.githubusercontent.com/37159441/66187856-6a057d80-e68e-11e9-8abe-732586bb7a17.jpg)

**Comment by serhatbolsu** [comment]
In order this library to update first it is bind to python_appium. I have check and verified that there is no change in that side. I suggest you to check appium forums/discussion boards. I should be something general regardless of robotframework implementation.
