### ISSUE TITLE
Add capabilities to handle Mobile Browser. e.g. Switch windows, Get Window Handles, Select From List etc

### ISSUE THREAD

**Issue by MandyYdnam** [serhatbolsu/robotframework-appiumlibrary#267]

**Comment by MandyYdnam** [comment]
We are trying to use this library for Mobile web but seems like switch to windows and select from drop down list is missing from the KW library.

**Comment by joshuariveramnltech** [comment]
Hi @MandyYdnam , by Mobile Web do you mean testing through Mobile Browsers like Chrome, Firefox, etc?

**Comment by MandyYdnam** [comment]
Hi @joshuariveramnltech. Yes. That’s correct.

**Comment by MandyYdnam** [comment]
I already have the workaround but It ll be good if these kw are added to library.

**Comment by joshuariveramnltech** [comment]
@MandyYdnam, what did you use as a workaround? I am currently using SeleniumLibrary to do mobile browser automation.

**Comment by serhatbolsu** [comment]
@MandyYdnam  would you mind working an implementation and open a pull request?

**Comment by MandyYdnam** [comment]
@serhatbolsu. Sure thing. Will start working on this.

**Comment by MandyYdnam** [comment]
I am done with the changes for switch window and get window handles. Let me know how can stare the code.

**Comment by serhatbolsu** [comment]
Please fork the repo, commit your change in your fork. Then you can create a pull request
