### ISSUE TITLE
Unable to run appium server through Robot Framework/python

### ISSUE THREAD

**Issue by QAthulhu** [serhatbolsu/robotframework-appiumlibrary#268]
I'm trying to create a script to programmatically open Appium server.

OS: Mac OS X 10.14.6
Python: 3.7.4
Node: 12.11.0
NPM: 6.11.3
Virtualenv: 16.7.5
Robot Framework: 3.1.2
Robot Framework Appium Library: 1.5.0.4
Appium: 1.15.0

I created a python script that imports AppiumService and use start() to run the server, but then I get the error 
`from appium.webdriver.appium_service import AppiumService`
even when NodeJS is in my path

Here's what the python script looks like
`from appium.webdriver.appium_service import AppiumService

class AppiumUtil:

    def __init__(self):

        self.appium_service = AppiumService()

    def connect(self):

        self.appium_service.start()`

My RF resource uses AppiumUtil as a Library and calls Connect. Looking at the documentation, the start() function in AppiumService allows a keyword argument to specify the node path, which I provided:
`self.appium_service(node="/usr/local/bin/")`
But when I run the code, I get a new error, this time saying NPM cannot be found and should be included in the PATH, even though it is.

Here is my PATH from echo $PATH:
`/usr/local/Cellar/maven/3.6.2/bin:/usr/local/Cellar/gradle/5.6.2/bin:/Users/[myname]/Library/Android/sdk/bundle-tool:/Users/[myname]/Library/Android/sdk/tools/bin:/Users/jamestoplis/Library/Android/sdk/tools:/Users/[myname]/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin:/usr/local/bin:/usr/local/sbin**:/usr/local/bin**:/usr/bin:/bin:/usr/sbin:/sbin`

/usr/local/bin is included there (tried to make it bold that's why it has **)

Using which node, which npm, I get this:
`/usr/local/bin/node
/usr/local/bin/npm`

I'm working on Eclipse with Red editor and I'm using a virtual environment created by virtualenv and the Python and Robot Framework installation I'm using is pointed to it at /Users/[myname]/.virtualenvs/myvenv/bin. 

Eventually I found a workaround by simply calling Appium through the terminal with
`os.system("/usr/local/bin/appium -a 127.0.0.1 -p 4723 &")`

It works as a standalone python script on my desktop, but running it through Robot Framework as a library results in similar errors (No Node, NPM, etc)

Is there something wrong with my pathings?

**Comment by serhatbolsu** [comment]
I have another suggestion for you. 
why not write a shell script that will start appium server (and whatever else you would like). 

Then just call the script inside the RF test case.

**Comment by serhatbolsu** [comment]
Since this is not the purpose of this library, closing the issue
