### ISSUE TITLE
is it possible to use the execute_script("mobile: selectPickerWheelValue", {'order': 'previous', 'offset': 0.15, 'element': element})

### ISSUE THREAD

**Issue by simplezhang1990** [serhatbolsu/robotframework-appiumlibrary#270]
is it possible to use the execute_script("mobile: selectPickerWheelValue", {'order': 'previous', 'offset': 0.15, 'element': element})

**Comment by tremkonzah** [comment]
@simplezhang1990 do you have a solution for this?
