### ISSUE TITLE
what is the meanin of "elif "(level == 'HTML')" in _logging.py?

### ISSUE THREAD

**Issue by fuheperpromise** [serhatbolsu/robotframework-appiumlibrary#272]
def _log(self, message, level='INFO'):
        level = level.upper()
        if (level == 'INFO'):
            self._info(message)
        elif (level == 'DEBUG'):
            self._debug(message)
        elif (level == 'WARN'):
            self._warn(message)
        elif (level == 'HTML'):
            self._html(message)

what is the meaning of level == 'HTML'?
why the level has HTML?

**Comment by serhatbolsu** [comment]
Hi @fuheperpromise . This is because of html encoding used for screenshots and now videos. Altough by convention it is not correct, no harm done
