### ISSUE TITLE
Can AppiumLibrary add screen recording ?

### ISSUE THREAD

**Issue by sidarakeo** [serhatbolsu/robotframework-appiumlibrary#273]
I'm also looking the way to record screen while testing. as i check in Appium there was a built-in function `self.driver.start_recording_screen()`. my suggestion RF-AppiumLibrary should add this.
Thanks

**Comment by joshuariveramnltech** [comment]
This would be good, will create a PR for this.  

BTW, Appium screen recording has a limitation that differs for Android and iOS. 

```
The default value for both iOS and Android is 180 seconds (3 minutes).
The maximum value for Android is 3 minutes.
The maximum value for iOS is 10 minutes.
```

**Comment by joshuariveramnltech** [comment]
@serhatbolsu created a PR for this.  https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/277.
