### ISSUE TITLE
Keeping Appium alive while running a test suite with BrowserStack

### ISSUE THREAD

**Issue by bjanzen** [serhatbolsu/robotframework-appiumlibrary#274]
It's a bit expensive to startup a new phone on BrowserStack for each test.  Looking for suggestions for keeping App connection alive between tests in a suite, instead of writing something in Python.

**Comment by serhatbolsu** [comment]
As I understand, you dont want to close and open app between each test case.
You dont actually need to close the app @bjanzen between test cases. You can keep executing with one `Open Application` however its not suggested as you wont be able to control test case execution, capture individual test case results
