### ISSUE TITLE
AppiumLibrary is not compatible with the new RF 3.2

### ISSUE THREAD

**Issue by zastress** [serhatbolsu/robotframework-appiumlibrary#279]
After installing RF 3.2 rc1 it seems that AppiumLibrary no longer works. I am guessing it has something to do with Python 3 compatibility.
Below 2 errors:
`Keyword 'AppiumLibrary.Set Appium Timeout' expected 2 arguments, got 1.`
`Keyword 'AppiumLibrary.Close All Applications' expected 1 argument, got 0.`

**Comment by laojala** [comment]
Also, Keywords Open Application and Remove Application fail with this error message:
`Keyword 'AppiumLibrary.Open Application' expected 2 to 3 non-named arguments, got 1.`

**Comment by zastress** [comment]
Found a temporary solution for this inside this MR: https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/177

So, to make this work with RF 3.2, do the following:
- Pull/download files at this commit state: https://github.com/serhatbolsu/robotframework-appiumlibrary/tree/3e2586208b5d593a874a15d539a56fd41a22924c
- Extract the zip archive and open the containing folder
- Run in terminal: `python setup.py install --user`

Now tests are working with RF 3.2.
Downside is that this MR is dated AppiumLibrary version 1.4.4. We'll see if problems appear

**Comment by zastress** [comment]
@serhatbolsu , any update planned for this issue?

**Comment by serhatbolsu** [comment]
I am planning to fix this, this weekend.

**Comment by laojala** [comment]
> I am planning to fix this, this weekend.

We are currently running the Appium library (1.5.0.6) with the latest RF (3.2.1) and it works without problems.

(sidenote: thank you for the new screen recording keywords - we are storing recordings of all failed tests)

**Comment by serhatbolsu** [comment]
I have run a check for those keywords with following
```robotframework
*** Settings ***
Resource    ../resources/keywords.robot
Test Teardown  close all applications

*** Test Cases ***
Basic Demo
  Open App
  set appium timeout  8 seconds
  wait until page contains element  asdfadf
```

Test waited for 8 seconds and application closed on teardown. Please open another issue if you observe issue persist

**Comment by tranhoangnguyen193** [comment]
I met this issues with Robot Framework 3.2rc2, Appium 1.6.1, Python 3.9.
