### ISSUE TITLE
Keyword 'AppiumLibrary.Open Application' expected 1 to 2 non-keyword arguments

### ISSUE THREAD

**Issue by ghost** [serhatbolsu/robotframework-appiumlibrary#28]
The test can run sccess on robotframework-appiumlibrary (1.0.22), but upgrade appiumlibrary to 1.2.0. then error:

```
==============================================================================
Open App                                                              | FAIL |
Keyword 'AppiumLibrary.Open Application' expected 1 to 2 non-keyword arguments,
got 5.
------------------------------------------------------------------------------
```

Test Script:

```
*** Settings ***
Library           AppiumLibrary

*** Variables ***
${REMOTE_URL}     http://localhost:4723/wd/hub
${PLATFORM_NAME}    Android
${PLATFORM_VERSION}    4.4.2
${DEVICE_NAME}    emulator-5554
${APP}            D:/asas.apk

*** Test Cases ***
Open App
    Open Application    ${REMOTE_URL}    ${PLATFORM_NAME}    ${PLATFORM_VERSION}    ${DEVICE_NAME}    ${APP}
    Sleep   10s 
```

**Comment by nomore001** [comment]
http://jollychang.github.io/robotframework-appiumlibrary/doc/AppimuLibrary.html#Open%20Application

Link is not found  I stuck with this key word,please help.

thank you

**Comment by jollychang** [comment]
http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html#Open%20Application

**Comment by nomore001** [comment]
Hi William Zhang,

I've some problem with use robotframework-appiumlibrary and create script
with RIDE,Could you tell me how to solve this problem with the red line
that picture i attached.

Thank you.



2015-08-31 20:15 GMT+07:00 William Zhang <notifications@github.com>:

>
> http://jollychang.github.io/robotframework-appiumlibrary/doc/AppiumLibrary.html#Open%20Application
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jollychang/robotframework-appiumlibrary/issues/28#issuecomment-136367905>
> .
>



-- 
*Best Regards,*

*Mr.Nuntapol Paholyuth (Bond)*
T.0875657381
