### ISSUE TITLE
Launch & Quit Application

### ISSUE THREAD

**Issue by Monahonkanen** [serhatbolsu/robotframework-appiumlibrary#280]
I try to open and close mobile application between testcases. I have some problems with it. This doesn't work because test suite gets stuck with second testcase:

*** Settings ***
Library             AppiumLibrary
Suite Setup         Open Application        http://localhost:4723/wd/hub        platformName=Android            platformVersion=8.0.0        
                    ...     deviceName= 8NH4C17214000986        automationName=uiautomator2      
                    ...     app=C:/Users/honka/AndroidStudioProjects/BMIApp/app/build/outputs/apk/debug/app-debug.apk    
                    ...     appPackage=fi.example.bmiapp     appActivity=fi.example.bmiappesp.MainActivity
Test Setup          Launch Application
Test Teardown       Quit Application
Suite Teardown      Close Application

If I change the code to this it works but it is very slow:

*** Settings ***
Library             AppiumLibrary
Test Setup         Open Application        http://localhost:4723/wd/hub        platformName=Android            platformVersion=8.0.0        
                    ...     deviceName= 8NH4C17214000986        automationName=uiautomator2      
                    ...     app=C:/Users/honka/AndroidStudioProjects/BMIApp/app/build/outputs/apk/debug/app-debug.apk    
                    ...     appPackage=fi.example.bmiapp     appActivity=fi.example.bmiappesp.MainActivity
Test Teardown          Close Application

What is the right way to use Launch Application and Quit Application in this? I think Launch and Quit would be faster way than open and close application because Launch and quit doesn't close the webdriver session.

**Comment by zastress** [comment]
Hello,

FIrst of all, you could try creating a keyword for just Opening the application, something like:

`Open My Application
     Open Application  http://localhost:4723/wd/hub  platformName=Android  platformVersion=8.0.0  deviceName= 8NH4C17214000986   automationName=uiautomator2  app=C:/Users/honka/AndroidStudioProjects/BMIApp/app/build/outputs/apk/debug/app-debug.apk  appPackage=fi.example.bmiapp   appActivity=fi.example.bmiappesp.MainActivity`

Then, you can have something like this in the Suite Setup:
`Suite Setup   Open My Application`

Second, if starting and quitting the application does not work, there is a way to start it more rapidly. You can add this capability when starting appium server or directly into the `Open Application` keyword: `skipDeviceInitialization=true`. This will ignore the installation of applium application and uiautomator server and client to the phone before actually starting the application.

Hope this helps.

**Comment by Monahonkanen** [comment]
Thank you for your reply. Those suggestions speed the process about 13 s. Now it takes to execute 5 test cases about 2 min and 9 s! I think it is pretty slow still. I know that this Open Application and Close Application opens and closes webdriver connection too. I still wonder why Launch Application and Quit Application doesn't work? It would just close and open the app, not the connection. Once it worked for 3 test cases and then it got stuck. And next time it got stuck with 2 test case; and nothing changed between!

**Comment by zastress** [comment]
You can try one more thing, see if it works: change the default SystemPort used by Appium for Android tests: `systemPort=8201`. The default is 8200 so you may get better results having all requests from your app sent to a new port.

**Comment by zastress** [comment]
Just out of curiosity: Are you using a Windows machine? If so, when it gets stuck, are you seing any Appium logs going trough the console?

**Comment by Monahonkanen** [comment]
Yes, Windows 10! Here is example what Appium is doing while it get stuck (last lines):
[debug] [ADB] Running 'C:\Users\honka\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 8NH4C17214000986 shell am start -W -n fi.example.bmiapp/fi.example.bmiappesp.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[debug] [W3C (300ffeab)] Responding to client with driver.launchApp() result: null
[HTTP] <-- POST /wd/hub/session/300ffeab-c579-4bd7-9ddd-45b8587a3101/appium/app/launch 200 1676 ms - 14
[HTTP]
[HTTP] --> GET /wd/hub/session/300ffeab-c579-4bd7-9ddd-45b8587a3101/source
[HTTP] {}
[W3C (300ffeab)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/300ffeab-c579-4bd7-9ddd-45b8587a3101/source' to command name 'getPageSource'[debug] [WD Proxy] Proxying [GET /wd/hub/session/300ffeab-c579-4bd7-9ddd-45b8587a3101/source] to [GET http://127.0.0.1:8200/wd/hub/session/9844e25f-34c4-40e3-8454-1bd43d2d83c7/source] with body: {}

**Comment by zastress** [comment]
Just a dumb idea but I have seen this behavior on my side a few times. This has nothing to do with Appium or your mobile device.
Try this: When the test gets stuck, go to the terminal where appium is running and hit the ENTER key. Same for the terminal where you launched the robot command. It might surprise you that the test will actually continue :). This problem does not occur on Linux or Mac, just on Windows.

**Comment by Monahonkanen** [comment]
I tried this ENTER key thing but test didn't continued.

**Comment by serhatbolsu** [comment]
closing as it seems resolved query
