### ISSUE TITLE
How to find element of android and iOS APP through Appium's function findElementByImage?

### ISSUE THREAD

**Issue by fengnex** [serhatbolsu/robotframework-appiumlibrary#283]
Within robot's test case, I currently want to find UI elements with the help of findElementByImage, which is released in v1.9.0 of appium in August, 2018.

I wonder whether we can use the function now and how to implement it if appiumlibrary has already supported. Any idea or example is appreareated! Thanks in advance.

**Comment by renukachandra** [comment]
I also have not been able to find `findElementByImage()`  implemented in robotframework.

**Comment by joshuariveramnltech** [comment]
@fengnex @renukachandra 
Was able to implement ``find_elements_by_image()`` from [appium/python-client](https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/search_context/mobile.py). Could check my PR? https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/291

I've tested it on an android app. Not sure if it will work for iOS, for i have no iOS test device. Thanks.

**Comment by serhatbolsu** [comment]
Merged to master
