### ISSUE TITLE
no open application ( DesktopLibrary + AppiumLibrary )

### ISSUE THREAD

**Issue by MoniRaj1** [serhatbolsu/robotframework-appiumlibrary#284]
Hi 

I have the main robot file where I m opening my application ( Desktop app ) , and through a keyword call in my test case I call the function that is defined in a different file which imports the DesktopLibrary( which has access to AppiumLibrary ).

But I get no open application error.

snippet:
test.robot
--------------------------------------------------------------------------------------------------
Settings 
Library       file.py
Keywords
Start App
    Open Application    ${REMOTE_URL}    ${platformName}       ${deviceName}    ${app}
Test Cases
 Test Case 1
    Test Step1 
------------------------------------------------------------------------------------------------

file.py
import DesktopLibrary
def Test_Step1():
       DesktopLibrary.Anyfunction()
-----------------------------------------------------------------------------------------------

**Comment by serhatbolsu** [comment]
@MoniRaj1  please check the example and sample project, if that doesnt work this concerns DesktopLibrary
