### ISSUE TITLE
Consider using something like Release Drafter 

### ISSUE THREAD

**Issue by Wolfe1** [serhatbolsu/robotframework-appiumlibrary#287]
Just a suggestion: https://github.com/marketplace/actions/release-drafter

Was happy to see a new version out today and immediately went to look for the release notes...which there were none. Something like Release Drafter would help users not have to dig through commits or search for which specific pull requests are in a release.

**Comment by serhatbolsu** [comment]
Thank you @Wolfe1  this is good suggestion, will check it out
