### ISSUE TITLE
Swipe not working with AppiumLibrary 1.5 on native view

### ISSUE THREAD

**Issue by arjunravi-locus** [serhatbolsu/robotframework-appiumlibrary#288]
Swipe keyword not performing the swipe action despite providing the appropriate bounds.

**Comment by serhatbolsu** [comment]
```robotframework
Swipe test
  open app
  click text   Views
  # swipe up action
  swipe  500  300  0  100  1000
```

i checked and it seems to be working with 
robotframework-appiumlibrary==1.5.0.6
robotframework==3.2.1
Appium-Python-Client==1.0.2
