### ISSUE TITLE
Capture Screenshot is not embedding appium-screenshot-1 into log.html on Windows Server 2012 R2

### ISSUE THREAD

**Issue by GeeFung** [serhatbolsu/robotframework-appiumlibrary#289]
OS: Microsoft Windows Server 2012 R2

RF: 3.1.2
AppiumRF: 1.5.0.4

**Comment by GeeFung** [comment]
![Screen Shot 2020-06-29 at 9 21 43 AM](https://user-images.githubusercontent.com/20116630/86019872-cbc00180-b9ec-11ea-8163-0038ee4d634c.png)

**Comment by GeeFung** [comment]
![Screen Shot 2020-06-29 at 9 21 43 AM](https://user-images.githubusercontent.com/20116630/86020189-33764c80-b9ed-11ea-8df1-9a2c6ba27eea.png)

**Comment by joshuariveramnltech** [comment]
@GeeFung was the screenshot taken at all?

**Comment by GeeFung** [comment]
@joshuariveramnltech screenshots all appear fine in the correct folder directory with the .html .xml etc.. The context is NATIVE_APP and actually I don't think context should matter here since this capture page screenshot will automatically take a screenshot of the device screen upon failure with Robot Framework. On macOS catalina running the same test case and same context the screenshot appears embedded fine no issues.

**Comment by serhatbolsu** [comment]
@GeeFung do you see any error log? 
I dont have windows to test, can ask help on this.

**Comment by j1000** [comment]
Downgrading to 1.4.6 fixed this issue for me (previously I had 1.5.0.4). I'll try to pinpoint the version where this started breaking.

**Comment by serhatbolsu** [comment]
are you sure this is changing only with appiumlibrary version? I am guessing either python or robotframework has an issue with windows compatibility. I couldnt find any related what with 1.5

**Comment by 4nif** [comment]
I have the same issue too on Windows 10. I can see a screenshot taken and not appear in the HTML report file

![image](https://user-images.githubusercontent.com/31293565/122646732-eeda4880-d14a-11eb-993c-1d69fcc89440.png)

I use the latest version and downgrade to the 1.4.6 still have the same problem
No error in RF log so far, only screenshot not embedded to the report

latest version
```
Package                      Version
---------------------------- -------
Appium-Python-Client         1.2.0
decorator                    5.0.9
docutils                     0.17.1
kitchen                      1.2.6
pip                          21.1.2
robotframework               4.0.3
robotframework-appiumlibrary 1.6.1
selenium                     3.141.0
setuptools                   57.0.0
six                          1.16.0
urllib3                      1.26.5
```

downgrade version
```
Package                      Version
---------------------------- -------
Appium-Python-Client         1.2.0
decorator                    5.0.9
docutils                     0.17.1
kitchen                      1.2.6
pip                          21.1.2
robotframework               4.0.3
robotframework-appiumlibrary 1.4.6
selenium                     3.141.0
setuptools                   57.0.0
six                          1.16.0
urllib3                      1.26.5
```

**Comment by serhat-onedio** [comment]
@4nif @j1000  please try now with v1.6.2

**Comment by serhatbolsu** [comment]
@j1000 @4nif please try now with v1.6.2

**Comment by 4nif** [comment]
Thanks @serhatbolsu, works now after upgrade to 1.6.2

**Comment by serhatbolsu** [comment]
You can add to after test and capture screenshot if test failed
