### ISSUE TITLE
Start Screen Recording keyword fails if Android does not support screenrecord utility

### ISSUE THREAD

**Issue by laojala** [serhatbolsu/robotframework-appiumlibrary#293]
`Start Screen Recording` fails in some Android's (seems to happen in all Huawei's) and thus the whole test case fails. 

Error in the log:
```
Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The expected screen record file '/sdcard/1595591647001.mp4' does not exist after 5000ms. Is screenrecord utility available and operational on the device under test?
```
Is this a bug? Could the keyword be more error-prone if there is no support for screenrecord utility? @joshuariveramnltech

**Workaround:**

Keyword can be run using BuiltIn keyword `Run Keyword And Return Status` or `Run Keyword And Ignore Error`.

**Comment by serhatbolsu** [comment]
a good approach can be to test this with `Appium-Python-Client` library
I can not test since I dont have Huawei device.

**Comment by joshuariveramnltech** [comment]
> Start Screen Recording fails in some Android's (seems to happen in all Huawei's) and thus the whole test case fails.  

@laojala might be an issue with *Huawei* Devices.  
Someone tested the keyword before and claimed he experienced issues with *Oppo* Devices, though he did not provide his error logs. Could check it here: https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/277#issuecomment-601512879

> Setup failed:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The expected screen record file '/sdcard/1595591647001.mp4' does not exist after 5000ms. Is screenrecord utility available and operational on the device under test?

Can you provide the Appium Server Logs during your test run?  
  
>Workaround:
Keyword can be run using BuiltIn keyword Run Keyword And Return Status or Run Keyword And Ignore Error.  

Yes, you could implement this as a way to avoid the whole test suite to fail if the target device not support screen recording.

**Comment by laojala** [comment]
> Can you provide the Appium Server Logs during your test run?

This happens when I start recording using the `Start Screen Recorind`keyword:
```
[HTTP] --> POST /wd/hub/session/0df297e1-5f89-4029-a364-2ad6f298d391/appium/start_recording_screen
[HTTP] {"options":{"timeLimit":180}}
[debug] [W3C (0df297e1)] Calling AppiumDriver.startRecordingScreen() with args: [{"timeLimit":180},"0df297e1-5f89-4029-a364-2ad6f298d391"]
[debug] [ADB] Getting IDs of all 'screenrecord' processes
[debug] [ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s CLCDU18911002838 shell pgrep -f screenrecord'
[AndroidDriver] Screen recording has not been previously started by Appium. There is nothing to stop
[debug] [ADB] Getting IDs of all 'screenrecord' processes
[debug] [ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s CLCDU18911002838 shell pgrep -f screenrecord'
[debug] [ADB] Building screenrecord process with the command line: adb -P 5037 -s CLCDU18911002838 shell screenrecord --time-limit 180 /sdcard/1595931299238.mp4
[debug] [ADB] Running '/Users/xxx/Library/Android/sdk/platform-tools/adb -P 5037 -s CLCDU18911002838 shell ls /sdcard/1595931299238.mp4'
...
[debug] [W3C (0df297e1)] Encountered internal error running command: Error: The expected screen record file '/sdcard/1595931299238.mp4' does not exist after 5000ms. Is screenrecord utility available and operational on the device under test?
[debug] [W3C (0df297e1)]     at scheduleScreenRecord (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/lib/commands/recordscreen.js:133:11)
[HTTP] <-- POST /wd/hub/session/0df297e1-5f89-4029-a364-2ad6f298d391/appium/start_recording_screen 500 5430 ms - 825
```

It seems that some devices do not simply provide this method for screen recording (and the only thing that could be catch from Appium is that `500`error response).

**Comment by joshuariveramnltech** [comment]
> It seems that some devices do not simply provide this method for screen recording (and the only thing that could be catch from Appium is that 500error response).  
Yup, seems that way.  

For now, I think `Screen Record` Keywords would only work on devices that supports screen record method. Also, if you have time, you could check https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/296.
  
Happy Coding!

**Comment by laojala** [comment]
Thank your support - I close this ticket now. 

Ending recording does not currently work - details here: https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/297
