### ISSUE TITLE
Ending screen recording fails in iPhone

### ISSUE THREAD

**Issue by laojala** [serhatbolsu/robotframework-appiumlibrary#297]
## To reproduce

1. Use iOS
2. Start capturing screen
3. End Capture using keyword `${filename} =   Stop Screen Recording`
4. **Bug:** Ending capture fails because filename is `None`. Error in the Robot Framework log:

```
AttributeError: 'dict' object has no attribute 'replace'
```
## Version details

This happens in the master (ie. does not happen in the released version). Head of the master is 0b05c7d66ac56ea3c1c04b937f2ea689173422e4.

Phone under test was iPhone7 (with quite a recent iOS)

## More info

The same keyword works in Android.

**Comment by joshuariveramnltech** [comment]
@laojala thanks for checking.

Can you provide the following info,
 * Appium Version
 * Appium Logs
  
Thanks!

**Comment by joshuariveramnltech** [comment]
@laojala 
Can test this?
https://github.com/joshuariveramnltech/robotframework-appiumlibrary/tree/fix-screenrecord-saving  
Thank you.

**Comment by laojala** [comment]
Yes @joshuariveramnltech this fixes ending recording in iOS (I also run it in Android and seems to work there too). Commit I used to run tests was :https://github.com/joshuariveramnltech/robotframework-appiumlibrary.git@f378d7d0be13f93b42c9306d578fe25daf5770bb

**Comment by laojala** [comment]
hahaa... now I know why my Android tests pass @joshuariveramnltech 😂 I am running those in a Docker and that image is using older version (so don't count on my testing *that* much). iOS tests in our CI create the environment from a scratch every time those are run.
