### ISSUE TITLE
Is it possible to use BrowserStack with your library 

### ISSUE THREAD

**Issue by jankowskimarcin** [serhatbolsu/robotframework-appiumlibrary#299]
Hello 

Question ?

Is it possible to use BrowserStack with your library  ?

Marcin

**Comment by serhatbolsu** [comment]
Yes you can  @jankowskimarcin, here you can find [local execution sample ](https://github.com/serhatbolsu/robotframework-appium-sample) . All you need is to follow browserstack documentation to connect their exposed remote devices.
