### ISSUE TITLE
Readme says "It is fully supported under Python 2.7."  but underlying appium-python-client is not.

### ISSUE THREAD

**Issue by rasjani** [serhatbolsu/robotframework-appiumlibrary#300]
For example: https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py#L88

afaik, those sort of typing hints will not work on 2.7 (at least not straight out of the box)..

**Comment by serhatbolsu** [comment]
Library developed in python 2.6 and recently upgrade to Python 3.x . you can create an issue if you come across a specific issue.

**Comment by rasjani** [comment]
Point being: Appium client that you fetch uses type hints. Even if your code could run on python 2.7,   Appium-Python-Client package that ends up being fetched via pip when installing will not.  

Even they advertize that 2.7 is not compatible: https://github.com/appium/python-client/blob/master/setup.py -- 3.7 and 3.8 are the only listed ones..

This leads to issues like this:

https://stackoverflow.com/questions/67305654/getting-an-error-while-trying-to-install-robotframework-appiumlibrary

All I'm saying is that if you advertise that its fully compatible with 2.7,  you need to ensure that your setup.py will not fetch appium  version that has deprecated 2.7 support by default ..

**Comment by serhatbolsu** [comment]
Thank you for suggestion and correct direction, I have updated setup.py accordinly as only python 3
