### ISSUE TITLE
Long Press not working on Android

### ISSUE THREAD

**Issue by zastress** [serhatbolsu/robotframework-appiumlibrary#301]
When I try to use the "Long Press" keyword, I am getting this error that I never seen before:
`InvalidArgumentException: Message: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 526.5 at line 1 column 44
 path $.params.y`

**Comment by serhatbolsu** [comment]
can you share the code you used as well?

**Comment by zastress** [comment]
@serhatbolsu it seems that this issue is no longer reproduced with Appium 1.19.1.
