### ISSUE TITLE
Release last change?

### ISSUE THREAD

**Issue by nantes44-github** [serhatbolsu/robotframework-appiumlibrary#302]
Hi, 

We are using appiumLibrary for robotframework, and we had an issue integrating allure reports. While looking for a solution, i saw that there are some enhancement and issues corrected but not released (the 'return path' in '_screenshot.py' for example) . 
Could you make a release when you can (so pip will be up to date too)?

Thanks in advance.

**Comment by joshuariveramnltech** [comment]
Hi @nantes44-github let us wait for serhatbolsu for the mean time. Thanks for using this library 😄 .

**Comment by serhatbolsu** [comment]
Version released thank you @nantes44-github @joshuariveramnltech
