### ISSUE TITLE
Element locator with prefix (//div[@class='ui fitted header truncate'])[0]' is not supported

### ISSUE THREAD

**Issue by mohamedmortdha** [serhatbolsu/robotframework-appiumlibrary#303]
i can't locate directly and element from list using (listelemnt)[indexelement] 
error locator with prefix is not suipported

**Comment by joshuariveramnltech** [comment]
@mohamedmortdha can provide error logs?

**Comment by wch352136** [comment]
> i can't locate directly and element from list using (listelemnt)[indexelement]
> error locator with prefix is not suipported

As far as I know, the index of xpath starts from 1,you can try to write like this (//div[@class='ui fitted header truncate'])[1]

**Comment by serhatbolsu** [comment]
Thank you
