### ISSUE TITLE
Swipe : Conversion problem between keyword and actions_helper

### ISSUE THREAD

**Issue by Cocognito** [serhatbolsu/robotframework-appiumlibrary#304]
Swipe doesn't work with String RF parameters (default behavior)

AppiumLibrary --> 1.5.0.7
Appium-Python-Client --> 1.0.2

Appium-Python-Client --> def swipe(self: T, start_x: int, start_y: int, end_x: int, end_y: int, duration: int = 0) -> T
Take int as parameter

AppiumLibrary --> driver.swipe(start_x, start_y, offset_x, offset_y, duration)
Send parameter as it receives it. No conversion. As RF default type are String, the keyword doesn't work

Compare to this, swipe by ercent is ok as there is a conversion parameter to float before calling action_helpers for example.

Swipe is working if RF parameters are convert to integers before calling Swipe Keyword.

Example not working ; 
Swipe | 100 | 100 | 100 | 100 | 2000

RF Report -> TRACE | Arguments: [ '100' \| '100' \| '100' \| '100' \| 2000 ] |  

Example working;
${myintx}  | convert to integer | 100
${myinty} | convert to integer | 100
${myintoffx} | convert to integer | 100
${myintoffy} | convert to integer | 100
Swipe | ${myintx} | ${myinty} | ${myintoffx} | ${myintoffy} | 2000

RF Report -> TRACE | Arguments: [ 100 \| 100 \| 100 \| 100 \| 2000 ]

Can you add an Int cast in Swipe Keyword to avoid this trick ?

**Comment by serhatbolsu** [comment]
Havent had this issue before, 
it is more then welcomed if you liked to make a Pull request about this
