### ISSUE TITLE
machine without internet connection installation error distutils.errors.DistutilsError

### ISSUE THREAD

**Issue by lovelyplanet2019** [serhatbolsu/robotframework-appiumlibrary#308]
I want to install RF offline due to my machine does not has internet connect. error on running.

C:\installers\RobotFramework for Pycharm\robotframework-appiumlibrary-master\robotframework-appiumlibrary-master>python setup.py install

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001ECDFB58DC0>: Failed to establish

a new connection: [Errno 11001] getaddrinfo failed')': /simple/pytest-runner/

WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001ECDFB58E20>: Failed to establish

a new connection: [Errno 11001] getaddrinfo failed')': /simple/pytest-runner/

WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001ECDFB1F4F0>: Failed to establish

a new connection: [Errno 11001] getaddrinfo failed')': /simple/pytest-runner/

WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001ECDFB1FF70>: Failed to establish

a new connection: [Errno 11001] getaddrinfo failed')': /simple/pytest-runner/

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001ECDFB1FFA0>: Failed to establish

a new connection: [Errno 11001] getaddrinfo failed')': /simple/pytest-runner/

ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)

ERROR: No matching distribution found for pytest-runner

Traceback (most recent call last):

  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg

    subprocess.check_call(cmd)

  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 364, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['C:\\Program Files\\Anaconda3\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\SIPO-T~1\\AppData\\Local\\Temp\\tmp07l_7y6g', '--quiet', 'pytest-r

unner']' returned non-zero exit status 1.

 

The above exception was the direct cause of the following exception:

 

Traceback (most recent call last):

  File "setup.py", line 11, in <module>

    setup(name='robotframework-appiumlibrary',

  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\__init__.py", line 152, in setup

    _install_setup_requires(attrs)

  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires

    dist.fetch_build_eggs(dist.setup_requires)

  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs

    resolved_dists = pkg_resources.working_set.resolve(

  File "C:\Program Files\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve

    dist = best[req.key] = env.best_match(

  File "C:\Program Files\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match

    return self.obtain(req, installer)

  File "C:\Program Files\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain

    return installer(requirement)

  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg

    return fetch_build_egg(self, req)

  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg

    raise DistutilsError(str(e)) from e

distutils.errors.DistutilsError: Command '['C:\\Program Files\\Anaconda3\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\SIPO-T~1\\AppData\\Local\\Temp\\tmp07l_7y6g', '--quiet', 'pytest

-runner']' returned non-zero exit status 1.

**Comment by Cocognito** [comment]
Hi,

setup.py indicates : 
setup_requires=[
          "pytest-runner"
      ]

So Python try to get it from Internet.
As you don't have Internet connection it fails and so the installation.

You nedd to manually install all dependances needed by AppiumLibrary.

So in your python librairies you also need all blow librairies before make the installation of AppiumLibray and their dependancies : 
      install_requires=[
          'decorator >= 3.3.2',
          'robotframework >= 2.6.0',
          'docutils >= 0.8.1',
          'Appium-Python-Client >= 0.28',
          'selenium >= 2.47.1',
          'kitchen >= 1.2.4',
          'six >= 1.10.0'
      ],
      tests_require=[
          'mock >= 2.0.0',
          'pytest-cov >= 2.5.1',
          'pytest-xdist >= 1.16.0',
          'pytest-pythonpath >= 0.7.1',
          'pytest >= 3.1.0',
          'six >= 1.10.0'
      ],

Hope that it helps.
Regards

**Comment by lovelyplanet2019** [comment]
thanks @Cocognito i will download them one by one. 
but i have already installed robotframework sucessfully. why it still need it?

**Comment by lovelyplanet2019** [comment]
if anybody have the exact github path for them? i google search and many similar name appeared.

**Comment by Cocognito** [comment]
I stupidly copy/paste the content of setup.py. So you if you have already installed it, it will be ok.

**Comment by lovelyplanet2019** [comment]
I edit main post, update latest log when i run it at pycharm terminal

**Comment by lovelyplanet2019** [comment]
i have installed all dependencies but still hitting same error. please help.

**Comment by lovelyplanet2019** [comment]
is that because of ananconda3 not compatible? i have install python client, robot framework sucessfully using the same method. just robot appium library does not install.

**Comment by Cocognito** [comment]
Do you have installed pytest runner ?

It seems this is what is looking for : 

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001ECDFB1FFA0>: Failed to establish

a new connection: [Errno 11001] getaddrinfo failed')': /simple/pytest-runner/

ERROR: Could not find a version that satisfies the requirement pytest-runner

**Comment by lovelyplanet2019** [comment]
thanks. issue resolved. install scm tools and py test runner first.
