### ISSUE TITLE
Getting an error while trying to install robotframework-appiumlibrary

### ISSUE THREAD

**Issue by amithrchandran** [serhatbolsu/robotframework-appiumlibrary#312]
Mac OS - 10.15.7
Python - 2.7.18

I used the command to install "pip install robotframework-appiumlibrary" and following is the error i get.

@Amiths-MacBook-Pro ~ % pip install robotframework-appiumlibrary
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting robotframework-appiumlibrary
  Using cached robotframework_appiumlibrary-1.5.0.7-py2.py3-none-any.whl (49 kB)
Collecting docutils>=0.8.1
  Using cached docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting decorator>=3.3.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting kitchen>=1.2.4
  Using cached kitchen-1.2.6.tar.gz (255 kB)
Collecting selenium>=2.47.1
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Requirement already satisfied: robotframework>=2.6.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from robotframework-appiumlibrary) (4.0.1)
Collecting Appium-Python-Client>=0.28
  Using cached Appium-Python-Client-1.1.0.tar.gz (53 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xn/c052lddx4qz1lm8h6thg0w_h0000gn/T/pip-install-IQfrSA/appium-python-client/setup.py'"'"'; __file__='"'"'/private/var/folders/xn/c052lddx4qz1lm8h6thg0w_h0000gn/T/pip-install-IQfrSA/appium-python-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/xn/c052lddx4qz1lm8h6thg0w_h0000gn/T/pip-pip-egg-info-AVKVXp
         cwd: /private/var/folders/xn/c052lddx4qz1lm8h6thg0w_h0000gn/T/pip-install-IQfrSA/appium-python-client/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xn/c052lddx4qz1lm8h6thg0w_h0000gn/T/pip-install-IQfrSA/appium-python-client/setup.py", line 19, in <module>
        from appium.common.helper import library_version
      File "appium/common/helper.py", line 20
        def extract_const_attributes(cls: type) -> Dict[str, Any]:
                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

@Amiths-MacBook-Pro ~ % python setup.py egg_info                
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by Cocognito** [comment]
The latest version of AppiumLibrary is not compatible with Python 2.7.
Update your python installation to 3.x if you want to work the latest appiumlibrary version.
Or indicates a appiumlibrary version that os compatible with python installation in your installation command.

**Comment by amithrchandran** [comment]
I had upgraded python to 3.7.7 and after that i was able to install without error.

Could you please do the needful to update the README ?

**Comment by serhatbolsu** [comment]
readme updated ,only supports python3
