### ISSUE TITLE
Add Extension/Plugin for AppiumLibrary for use with Sauce Labs

### ISSUE THREAD

**Issue by joshmgrant** [serhatbolsu/robotframework-appiumlibrary#317]
Hello. I would like to suggest adding some kind of integration with Sauce Labs with the AppiumLibrary.

Here's an example of how to use Sauce Labs with SeleniumLibary now:

https://github.com/saucelabs-training/demo-python/tree/main/examples/robotframework/native_mobile

I'd like to create some kind of library or integration that has higher-level keywords for specific use with Sauce Labs (eg `Open Sauce Android Device` in addition to `Open Application`). In the case of the SeleniumLibrary, there is a [plugin system](https://robotframework.org/SeleniumLibrary/#extending-seleniumlibrary) that allows uses to extend the SelenuimLibrary with additional keywords while users can still use the standard keywords. Is there some approach like this you'd recommend. Let me know what you think, I'm very much open to suggestions!

**Comment by serhatbolsu** [comment]
This is a good idea, @joshmgrant  I dont know when / how that we can add a plugin system. I would gladly participate if somebody starts the work. For the time being, you can fork and extend the library use it with the license. 

Meanwhile, saucelabs is already very easy to integrate, all you need to mention is the ip:port, token. 
I couple of ease of use keywords could be added. By the way, check out the sample library , writing some sample there is another good idea -> https://github.com/serhatbolsu/robotframework-appium-sample

**Comment by serhatbolsu** [comment]
@joshmgrant all you need to do is to change url and use sauce desired capabilities,
