### ISSUE TITLE
Unable to open any web application on a Perfecto mobilebrowser via robot

### ISSUE THREAD

**Issue by sayom88** [serhatbolsu/robotframework-appiumlibrary#323]
I have written the following robot script to launch the Safari browser and open the Perfecto portal. When I run this script, I am observing that the safari browser is getting launched on the iPhone,but the Perfecto portal is not launching. Can you please help me to resolve this. Tnx.

*** Settings ***
Library           AppiumLibrary    10
Library           PerfectoLibrary     RobotframeworkPerfectoBrowserDemoProject        v1.0         RobotframeworkPerfectoBrowserDemoJob       1

*** Variables ***
${perfecturl}     https://<your_cloud_name>.perfectomobile.com/nexperience/perfectomobile/wd/hub/fast
${token}          <your_perfecto_security_token>
${bundleId}       com.apple.mobilenotes
${deviceid_iphone}   <your_device_id>

*** Test Cases ***
Demo test on iphone
    [Tags]    Perfeco  Device   iPhone
    [Teardown]   Close All Applications
    open test device and launch mobilebrowser      iPhone
    

*** keywords ***
open test device and launch mobilebrowser
[arguments]     ${devicemodel}
    run keyword if  '${devicemodel}'=='iPhone'     open application    ${perfecturl}   securityToken=${token}    deviceName=${deviceid_iphone}      noReset=${True}   browserName=mobileOS   browserUrl=https://perfecto.io

**Comment by serhatbolsu** [comment]
did you try making it work in local device first? make sure this is actually because of perfecto , then its not in the context of this library
