### ISSUE TITLE
Unable to select iOS picker wheel value

### ISSUE THREAD

**Issue by qe360-vrucenzon** [serhatbolsu/robotframework-appiumlibrary#326]
Hello! I encountered [this same problem](https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/119).

Environment:
- Appium v1.21.0
- OSX 11.5.1 (M1 chip)
- Node v14.17.5
- iPhone 12 Pro Max (iOS 14.5), simulator
- appiumlibrary for robotframework.

Tried using both `Input Text` and `Input Value` but no luck.

For additional context, I encountered this on the native iPhone calendar app (com.apple.mobilecal)

<img width="1438" alt="Screen Shot 2021-08-31 at 4 48 32 PM" src="https://user-images.githubusercontent.com/86818474/131472698-ade5e50b-b851-466b-98c4-f2bc0da619a7.png">

**Comment by serhatbolsu** [comment]
please write a test case with python-client if you can achieve this , I don't think its possible. Years back I did with swipe
