### ISSUE TITLE
Flutter app

### ISSUE THREAD

**Issue by tremkonzah** [serhatbolsu/robotframework-appiumlibrary#327]
Hi @serhatbolsu 

Wondering if I can use this library for Flutter App?
From my quick test I am able to open flutter app, however I am not able to perform click element etc

I use Appium Desktop to locate the element

Is there any work around to be able to use this library for Flutter App?

**Comment by marcosmko** [comment]
Hello!

I'm also trying to use this library for flutter app. Will come back later if I discover something.

**Comment by marcosmko** [comment]
I've discovered another library that can help us ;)
https://github.com/igortavtib/robotframework-appiumflutterlibrary
