### ISSUE TITLE
Deeplink with appiumlibrary to open the app

### ISSUE THREAD

**Issue by tremkonzah** [serhatbolsu/robotframework-appiumlibrary#330]
Hello @serhatbolsu 

Would be possible to open a deeplink and trigger to open the app?
Something like AppiumLibrary.Go to Url    <provide_mobile_deeplink>

If this is not possible any workaround that I can to to click on the deeplink and open mobile app?

**Comment by serhatbolsu** [comment]
is this a feature of Appium underlying ios/android drivers? only then it can be implemented

**Comment by Aledosim** [comment]
In my case, it's the easiest way to test React Native apps with Expo during development (without building an apk).
On code of C# and JavaScript clients I found a sort of "execute" function, with which you can execute adb shell commands. Then a command to open the deeplink pointing to the app under test is run. So I think it's not hard to implement.
The workaround I'm trying is to use `Execute Adb Shell` keyword to run the deeplink command. I'm studying, if anyone have some tips on how to use it.

**Comment by serhatbolsu** [comment]
fixed with #363 please test, you can use `mobile: deepLink` for UIAutomator2 check other mobile commands. https://appium.io/docs/en/commands/mobile-command/
