### ISSUE TITLE
Failed to establish a new connection: [Errno 61] Connection refused'

### ISSUE THREAD

**Issue by juanzebra** [serhatbolsu/robotframework-appiumlibrary#331]
I'm having this warn and failures in my automated tests cases which are set with:
```
*** Settings ***

Library     AppiumLibrary
```

When using the **Open App** keyword from the AppiumLibrary

![image](https://user-images.githubusercontent.com/85249534/135891798-b0294a03-2be3-4d98-8b11-d000d606bea0.png)

Any idea how to resolve this issue??

**Comment by serhatbolsu** [comment]
are you sure your appium server is running?
