### ISSUE TITLE
current version (1.6.3) restricts use of robotframework-seleniumlibrary above 5.1.3

### ISSUE THREAD

**Issue by axi92** [serhatbolsu/robotframework-appiumlibrary#335]
I have a weird issue that I can not find the cause.
I get the error `AttributeError: can't set attribute` on `Open Application` but what attribute?
```
    ${appium_app_index}=    AppiumLibrary.Open Application    http://${APPIUM_SERVER_IP}:${APPIUM_SERVER_PORT}/wd/hub
    ...    platformName=Android    platformVersion=8.1.0    deviceName=${TABLET_IP}:${TABLET_PORT}    app=${app_file}    appPackage=${app_package}
    ...    appActivity=${TABLET_APP_ACTIVITY}    automationName=UIAutomator2    newCommandTimeout=600
```
![grafik](https://user-images.githubusercontent.com/1394837/156740242-568c101e-2c2b-4fd2-b582-e19e3ac1fb49.png)
Versions:
robotframework==4.1.3
robotframework-appiumlibrary==1.6.3
Appium version: appium@1.15.1 now upgraded to 1.22.2 installed with npm
appium-uiautomator2-driver@1.38.0 now upgraded to 2.0.3
Both upgrades for appium and uiautomator2-driver did not change the error.
Python 3.8.0

I could not find the supported appium versions, will be appium 2.0 also supported? https://github.com/appium/appium/blob/2.0/docs/en/about-appium/1.x-eol.md

Appium log: https://gist.github.com/axi92/80fae1fe69f94d7ed2a6f7c85726e2df

Appium doctor:
```
redacted@robotmaster-vm:~$ appium-doctor 
info AppiumDoctor Appium Doctor v.1.6.0
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /home/redacted/.nvm/versions/node/v12.13.0/bin/node
info AppiumDoctor  ✔ Node version is 12.13.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: /opt/android/
info AppiumDoctor  ✔ JAVA_HOME is set to: /usr/lib/jvm/java-8-oracle
info AppiumDoctor  ✔ adb exists at: /opt/android/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /opt/android/tools/android
info AppiumDoctor  ✔ emulator exists at: /opt/android/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 
```

**Comment by axi92** [comment]
I debugged the _aaplicationmanagement.py file and found out that it breaks here https://github.com/serhatbolsu/robotframework-appiumlibrary/blob/master/AppiumLibrary/keywords/_applicationmanagement.py#L52

**Comment by axi92** [comment]
It was an incompatibility with higher selenium versions.
The problem is that robotframework-appiumlibrary uses https://github.com/appium/python-client Version: 1.1.0
And The [python-client v1.1.0 needs selenium <4.0.0](https://github.com/appium/python-client/blob/v1.1.0/setup.py)
So there is no way to use selenium at the same time above v4.0.0 but the latest [robotframework-seleniumlibrary needs. >4.0.0](https://github.com/robotframework/SeleniumLibrary/blob/master/requirements.txt#L1)

**Comment by serhatbolsu** [comment]
please check with #363  you can create new issue if still exists
