### ISSUE TITLE
Impossible to use locator for switching frame

### ISSUE THREAD

**Issue by szymonjaczkowski** [serhatbolsu/robotframework-appiumlibrary#341]
Hi! I'm using appium library to navigate through iframes in a web browser. I've got a session with an emulated android device. 
I checked how many iframes I have and I want to switch to one. 
```
@{IFRAMES}  Get Webelements  //iframe
FOR  ${IFRAME}  IN  @{IFRAMES}
    ${NAME}  Get Element Attribute  ${IFRAME}  Name
    Log To Console    ${NAME}
END
Switch To Frame   //*[@name="hosted-field-form"]
```
    
This for loop returns me 7 values and one of them is hosted-field-form. 
Test ends with failing switch to frame keyword and `InvalidArgumentException: Message: invalid argument: invalid locator
(Session info: chrome=91.0.4472.114)`

Could you please help me with finding a solution to this issue?

**Comment by serhatbolsu** [comment]
If you can create this scenario with generic test application so I can test it, I can help you
see the project -> https://github.com/serhatbolsu/robotframework-appium-sample
