### ISSUE TITLE
Version 1.6.3 of robotframework-appiumlibrary lib does not support version 2.0 of Appium-Python-Client

### ISSUE THREAD

**Issue by hllsouza** [serhatbolsu/robotframework-appiumlibrary#342]
Hi guys, I'm having a problem with appium. In the last few days, appium stopped recognizing elements of type ID, I managed to make them recognize through version 2.0 of Appium-Python-Client, but when I run it through my project using robot framework + robotframework-appiumlibrary, the capabilities settings [disableIdLocatorAutocompletion]=true is not being recognized as boolean, which I believe is incompatibility between robotframework-appiumlibrary and Appium-Python-Client versions. Can anyone support this problem?

**Comment by atenwolde** [comment]
have also problems with appium version 2.0 and appiumlibrary 1.6.3 any update on this issue?

**Comment by serhatbolsu** [comment]
I have update the library to at least being able to run while selenium4 is installed however still needs to fix some keywords

**Comment by serhatbolsu** [comment]
Test fix here please https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/363
