### ISSUE TITLE
Fix find element by xpath's strategy which got removed in selenium 4.3.0 version

### ISSUE THREAD

**Issue by vvelusamy1** [serhatbolsu/robotframework-appiumlibrary#344]
deprecated functions are removed in the selenium and hence the webdriver does not have the attribute find element by options.
https://github.com/SeleniumHQ/selenium/commit/4bbb7c255ae6991a65ba9878bee3941d23ecb951#diff-c87c150ed2a08f5293db58a06da8bf7f14c3a5582586c6270c1be661dfdd0985L456

 we need to update the appium library to resolve this? downgrading selenium to 4.2.0 from the latest version 4.3.0 works fine.

https://github.com/SeleniumHQ/selenium/releases

@jollychang Appreciate your thoughts on this.

**Comment by clarabez** [comment]
Same here:
With Selenium 4.3.0 I also see " 'WebDriver' object has no attribute 'find_element_by_id'" , as it was removed:
https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/py/CHANGES

So far, downgrading Selenium from 4.3.0 to 4.2.0 is working for me. I am waiting for the fix.

**Comment by zastress** [comment]
Explanation: https://pythoninoffice.com/fixing-attributeerror-webdriver-object-has-no-attribute-find_element_by_xpath/

**Comment by serhatbolsu** [comment]
fixed with #363  please test there .
