### ISSUE TITLE
Migrate to Githuh Actions

### ISSUE THREAD

**Issue by filipehb** [serhatbolsu/robotframework-appiumlibrary#349]
people, i was thinking of opening a PR with a workflow for whenever a PR is merged, a new release is created and published on pypi. What do you think?

**Comment by serhatbolsu** [comment]
There is a commit but doesn't seem to work , I have added secret as PYPI_API_TOKEN, feel free to fix the PR

**Comment by filipehb** [comment]
Nice! i will try to fix it
