### ISSUE TITLE
Selenium v4 not Working with Robot-Appium Library

### ISSUE THREAD

**Issue by Atwinenickson** [serhatbolsu/robotframework-appiumlibrary#362]
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_id' error returned when I run appium with robot framework and selenium v4.

**Comment by serhat-onedio** [comment]
I have update the library to at least being able to run while selenium4 is installed however still needs to fix some keywords

**Comment by serhatbolsu** [comment]
I have update the library to at least being able to run while selenium4 is installed however still needs to fix some keywords
