### ISSUE TITLE
Implement new ActionHelper#flick

### ISSUE THREAD

**Issue by serhatbolsu** [serhatbolsu/robotframework-appiumlibrary#365]
Implement new keyword `flick`  that does;
- refer to https://github.com/appium/python-client regarding implementation, 
also appium.webdriver.extensions.action_helpers

**Comment by joshuariveramnltech** [comment]
Hi @serhatbolsu https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/370

**Comment by serhatbolsu** [comment]
Fixed by @joshuariveramnltech
