### ISSUE TITLE
Updating to 2.0.0 causes No module found

### ISSUE THREAD

**Issue by sasasa42** [serhatbolsu/robotframework-appiumlibrary#369]
After I updated  the robotframework-appiumlibrary from 1.6.4 to 2.0.0, I started facing some issues in the logs as attached. Please let me know how to go about it.
<img width="709" alt="Screenshot 2022-11-08 at 3 41 41 PM" src="https://user-images.githubusercontent.com/30074470/200503481-8d14dbd9-77a6-4046-8089-3e1325bc986f.png">

**Comment by serhatbolsu** [comment]
@sasasa42 ty for the issue, 

Please paste the result of `pip list` from your environment

**Comment by serhatbolsu** [comment]
This library comes from `Appium-Python-Client         2.7.1` , very likely you have an earlier version somehow

**Comment by sasasa42** [comment]
yes..correct. It is due to the `Appium-Python-Client 2.7.1`. I shall close this ticket. sorry and Thanks!
