### ISSUE TITLE
Keyword 'AppiumLibrary.Click Element At Coordinates' is deprecated. But no alternative

### ISSUE THREAD

**Issue by atenwolde** [serhatbolsu/robotframework-appiumlibrary#380]
When i use "Click Element At Coordinates" than i get the following warning "Keyword 'AppiumLibrary.Click Element At Coordinates' is deprecated. Since selenium v4, use other keywords.", but i can't find a alternative for "Click Element At Coordinates"

**Comment by serhatbolsu** [comment]
Please check appium python client for a keyword, you can also submit a PR to update
