### ISSUE TITLE
robotframework-appium library install failed : No module named 'appium'

### ISSUE THREAD

**Issue by anlecoz** [serhatbolsu/robotframework-appiumlibrary#381]
Hello,

I have following issue when trying to install appium library :

pip install robotframework-appiumlibrary
Looking in indexes: http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/simple
Collecting robotframework-appiumlibrary
  Using cached http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/packages/robotframework-appiumlibrary/2.0.0/robotframework_appiumlibrary-2.0.0-py2.py3-none-any.whl (37 kB)
Collecting decorator>=3.3.2
  Using cached http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/packages/decorator/5.1.1/decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: robotframework>=2.6.0 in c:\python-3.11.2-embed-amd64\lib\site-packages (from robotframework-appiumlibrary) (6.0.2)
Requirement already satisfied: docutils>=0.8.1 in c:\python-3.11.2-embed-amd64\lib\site-packages (from robotframework-appiumlibrary) (0.19)
Collecting Appium-Python-Client>=2.7.1
  Using cached http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/packages/appium-python-client/2.8.1/Appium-Python-Client-2.8.1.tar.gz (3.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\b300tvz\AppData\Local\Temp\pip-install-kgs_7pk6\appium-python-client_1a1a180959e2486f95dac9782d186a75\setup.py", line 19, in <module>
          from appium.common.helper import library_version
      ModuleNotFoundError: No module named 'appium'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Here is my configuration of python, appium and installed libraries :

pip list
Package                        Version
------------------------------ ---------
async-generator                1.10
attrs                          22.2.0
certifi                        2022.12.7
cffi                           1.15.1
docutils                       0.19
h11                            0.14.0
idna                           3.4
outcome                        1.2.0
pip                            23.0.1
pycparser                      2.21
PySocks                        1.7.1
robotframework                 6.0.2
robotframework-pythonlibcore   4.1.2
robotframework-seleniumlibrary 6.0.0
selenium                       4.8.2
setuptools                     67.4.0
sniffio                        1.3.0
sortedcontainers               2.4.0
trio                           0.22.0
trio-websocket                 0.9.2
urllib3                        1.26.14
wheel                          0.38.4
wsproto                        1.2.0

python --version
Python 3.11.2

appium --version
1.22.3

appium-doctor
WARN AppiumDoctor [Deprecated] Please use appium-doctor installed with "npm install @appium/doctor --location=global"
info AppiumDoctor Appium Doctor v.1.16.2
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\JTB\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 18.14.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\b300tvz\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\JTB\jdk\jdk11.0.9_11
info AppiumDoctor      'adb' is in C:\Users\b300tvz\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor      'android' is in C:\Users\b300tvz\AppData\Local\Android\Sdk\tools\android.bat
info AppiumDoctor      'emulator' is in C:\Users\b300tvz\AppData\Local\Android\Sdk\emulator\emulator.exe
info AppiumDoctor      'apkanalyzer.bat' is in C:\Users\b300tvz\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\apkanalyzer.bat
info AppiumDoctor  ✔ adb, android, emulator, apkanalyzer.bat exist: C:\Users\b300tvz\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ 'bin' subfolder exists under 'C:\JTB\jdk\jdk11.0.9_11'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
WARN AppiumDoctor  ✖ gst-launch-1.0.exe and/or gst-inspect-1.0.exe cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 5 fixes possible. ###
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: http://appium.io/docs/en/writing-running-appium/image-comparison/
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it. Also consider adding the ".jar" extension into your PATH
EXT environment variable in order to fix the problem for Windows
WARN AppiumDoctor  ➜ gst-launch-1.0.exe and gst-inspect-1.0.exe are used to stream the screen of the device under test. Please read https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/ to install them a
nd for more details
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

Have you an idea to fix this issue ?
Thanks for your response

**Comment by serhatbolsu** [comment]
did you try the project https://github.com/serhatbolsu/robotframework-appium-sample ? 
it may be that python can not find appium installiation

**Comment by anlecoz** [comment]
Still same issue when installing appium-python-client package :

pip install -r requirements.txt
Looking in indexes: http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/simple
Requirement already satisfied: robotframework>=3.1.1 in c:\python-3.11.2-embed-amd64\lib\site-packages (from -r requirements.txt (line 1)) (6.0.2)
Collecting robotframework-appiumlibrary>=1.6.*
  Using cached http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/packages/robotframework-appiumlibrary/2.0.0/robotframework_appiumlibrary-2.0.0-py2.py3-none-any.whl (37 kB)
Collecting decorator>=3.3.2
  Using cached http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/packages/decorator/5.1.1/decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: docutils>=0.8.1 in c:\python-3.11.2-embed-amd64\lib\site-packages (from robotframework-appiumlibrary>=1.6.*->-r requirements.txt (line 2)) (0.19)
Collecting Appium-Python-Client>=2.7.1
  Using cached http://nexus-proxy.groupe.generali.fr/python/repository/pypi-all/packages/appium-python-client/2.8.1/Appium-Python-Client-2.8.1.tar.gz (3.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\b300tvz\AppData\Local\Temp\pip-install-9zitfycq\appium-python-client_6d0f303b9c4b4ffe9907e660c02cc296\setup.py", line 19, in <module>
          from appium.common.helper import library_version
      ModuleNotFoundError: No module named 'appium'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by serhatbolsu** [comment]
I would like to help you but it seems this issue is not relevant to this library, maybe check https://github.com/appium/python-client issues for solution
