### ISSUE TITLE
Appium-Python-Client 4.0.0 breaks this package.

### ISSUE THREAD

**Issue by rasjani** [serhatbolsu/robotframework-appiumlibrary#417]
Some asked about a problem in RF forums https://forum.robotframework.org/t/unable-to-import-robotframework-appiumlibrary-even-after-successful-installation-in-pycharm/6990

In their installed packages, Appium-Python-Client was reported to be 4.0.0 which was released yesterday.

On this project''s setup.py, that dependency is asked to be anything newer than so once 4.0.0 got released and it had deprecated some features (TouchAction) in this case, AppiumLibrary importing into robot framework fails.

**Comment by mliikanen** [comment]
Anyone bumping into this problem before https://github.com/rasjani/robotframework-appiumlibrary/commit/9f325a7535c0b6c52d52cab56da98097af45c018  is published, you can locally downgrade Appium-Python-Client to pre-4.0.0 version with  `pip install --force-reinstall "Appium-Python-Client<4.0.0"`

**Comment by HApolonio** [comment]
We've run into this issue also. Please fix it as soon as possible.

**Comment by HigorMamud** [comment]
Tive o mesmo problema só que no linux. 
A solução foi desinstalar a versão  4.0.0 e instalar uma mais antiga. Instalei a 3.0.0 e voltou a funcionar normalmente. Acredito que a versão anterior a 4.0.0 também funcione bem.

**Comment by serhatbolsu** [comment]
fixed with #398
