### ISSUE TITLE
Failed to import allium.webdriver.common.touch-action after installing latest version of Appium-Python-Client (4.0.0)

### ISSUE THREAD

**Issue by KulacTM** [serhatbolsu/robotframework-appiumlibrary#422]
Steps to reproduce:
1. Install Appium-Python-Client-4.0.0
2. Go to Settings where you call AppiumLibrary

Expected result: no errors
Actual result: error "Failed to import allium.webdriver.common.touch-action"

When I manually return to previously used version (2.9.0), it helps.

**Comment by lhimo** [comment]
See https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/417

**Comment by KulacTM** [comment]
Thanks, missed it

**Comment by KulacTM** [comment]
Tbd

**Comment by KulacTM** [comment]
Duplicate
