### ISSUE TITLE
404 error on documentation link

### ISSUE THREAD

**Issue by ps1logi** [serhatbolsu/robotframework-appiumlibrary#437]
We are getting a 404 error when selecting the below link

- [Appium Driver Setup Guide](http://appium.io/docs/en/about-appium/getting-started/?lang=en)
- [Appium Documentation](http://appium.io/docs/en/about-appium/getting-started/)
Please fix them

**Comment by emanlove** [comment]
Fixed in current code repository. This will bleed out into other sources (PyPI package readme, for example) after the next release.
