### ISSUE TITLE
Cannot find definition of utils.escape_xpath_value

### ISSUE THREAD

**Issue by CMTaylor** [serhatbolsu/robotframework-appiumlibrary#92]
This may be another of my stupid questions, but I'm getting an error
"AttributeError: 'module' object has no attribute 'escape_xpath_value'"
and when I search all the AppiumLibrary source code I can't find 'escape_xpath_value' defined anywhere, certainly NOT in the utils module.

Please explain and help me find this method!

**Comment by serhatbolsu** [comment]
I would guess this is a part of either robotframework or python appium client. Maybe @jollychang knows better

**Comment by serhatbolsu** [comment]
released with v1.4

**Comment by vyshnavij** [comment]
I tried entering text into edit text without clicking on edittext component initially and i got the same error.Then i tried clicking the edittext and then entered the text using input text keyword and it worked fine. 
This may be useful,if not please ignore this....

**Comment by serhatbolsu** [comment]
Sometimes it just works for some components it works as you said. This is a bug/feature req. on Appium side. Library should not monkey patch this.
