### ISSUE TITLE
Using Android's UI Automator as the locator

### ISSUE THREAD

**Issue by muruguvenkat** [serhatbolsu/robotframework-appiumlibrary#96]
I am trying to use UI Automator as the locator for clicking some elements in an Android app.  The snippet I'm trying to use is:

> Click Element  android=new UiSelector().description('arbitraryDescription')

From the documentation that looks like it should work.  However this fails every time with the following output:

> WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.

I'm largely confused because I'm distinctly not trying to call the WebDriver and I don't know why I'm getting that instead of the UI Automator.

**Comment by serhatbolsu** [comment]
I believe description is wrong. Since there is no "new" for library. 
Can you try the whole ´android=´ value as a string?
reference: [Python Appium Client Example](https://github.com/appium/python-client/blob/master/test/functional/android/appium_tests.py)

**Comment by muruguvenkat** [comment]
Wow you are absolutely correct:  Just so this is clear the following is what the documentation says should work:

`Click` Element android=new UiSelector().description('arbitraryDescription')

And this is what actually works:

`Click` Element android=UiSelector().description('arbitraryDescription')

**Comment by serhatbolsu** [comment]
Can you submit a pull request for this? You need to also create new documentation as well

**Comment by sabzwari1** [comment]
I am trying to click on an element for a hybrid app and using the following keyword

Click Element    android=UiSelector().index(0)      also tried 
android=UiSelector().description('. ')                     also tried
new UiSelector().index(0) 
But result is always same, not working.

I am getting the below error.
"
Status: FAIL (critical) 
Message: WebDriverException: Message: unknown error: Unsupported locator strategy: -android uiautomator
  (Session info: webview=33.0.0.0)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)
 
Start / End / Elapsed: 20160506 15:36:03.270 / 20160506 15:36:04.386 / 00:00:01.116 

00:00:01.111 KEYWORD AppiumLibrary . Click Element android=UiSelector().index(0) 
Documentation: Click element identified by `locator`.
 
Start / End / Elapsed: 20160506 15:36:03.273 / 20160506 15:36:04.384 / 00:00:01.111 

00:00:00.580 KEYWORD AppiumLibrary . Capture Page Screenshot Documentation: Takes a screenshot of the current page and embeds it into the log.
 
Start / End / Elapsed: 20160506 15:36:03.760 / 20160506 15:36:04.340 / 00:00:00.580 
15:36:04.339 FAIL WebDriverException: Message: unknown error: cannot activate web view
  (Session info: webview=33.0.0.0)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)
  

15:36:03.277 INFO Clicking element 'android=UiSelector().index(0)'.  
15:36:04.341 WARN Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: unknown error: cannot activate web view
  (Session info: webview=33.0.0.0)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)
  
15:36:04.383 FAIL WebDriverException: Message: unknown error: Unsupported locator strategy: -android uiautomator
  (Session info: webview=33.0.0.0)
  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)
 
"

Please suggest.

**Comment by serhatbolsu** [comment]
@sabzwari1  did you switch to Webview first? 
Regarding ; `Capture Screenshot` you must switch to Nativeview  for this keyword

**Comment by serhatbolsu** [comment]
Please open again if you still have problem, you can try new keywords with release v1.4
